//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSArray;

@interface AccessDeniedViewController : UITableViewController
{
    NSArray *_instructionStrings;
    NSArray *_instructionIcons;
}

- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)cellStyle;
- (int)gradientType;
- (id)instructionIcons;
- (id)instructionStrings;
- (id)detailText;
- (id)titleText;
- (void)viewDidLoad;
- (id)init;

@end

