//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AccountCheckViewController, NSString;

@protocol AccountCheckViewControllerDelegate <NSObject>
- (void)accountCheckViewController:(AccountCheckViewController *)arg1 wantsNewAccountWithPhoneNumber:(NSString *)arg2 countryCode:(NSString *)arg3 verificationCode:(NSString *)arg4;
- (void)accountCheckViewControllerDidLogIn:(AccountCheckViewController *)arg1;
@end

