//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ActionButton : NSObject
{
    NSString *_label;
    CDUnknownBlockType _action;
}

+ (id)itemWithLabel:(id)arg1;
+ (id)item;
@property(copy, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
- (void).cxx_destruct;

@end

