//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AnalyticsRegistrationWaterfallSession : NSObject
{
    NSString *_waterfallSessionID;
    unsigned int _lastAction;
    unsigned int _lastStep;
}

+ (id)currentWaterfallSession;
@property(nonatomic) unsigned int lastStep; // @synthesize lastStep=_lastStep;
@property(nonatomic) unsigned int lastAction; // @synthesize lastAction=_lastAction;
@property(copy, nonatomic) NSString *waterfallSessionID; // @synthesize waterfallSessionID=_waterfallSessionID;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL inSession;
- (void)endWaterfallSession;
- (void)startWaterfallSession;

@end

