//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface AnalyticsEvent : NSObject
{
    NSDictionary *_extras;
    NSString *_module;
    NSString *_event;
}

+ (id)addParamsToExtra:(id)arg1;
+ (void)logEventWithName:(id)arg1 withModule:(id)arg2 withExtra:(id)arg3;
+ (void)setupAnalytics;
+ (void)initialize;
+ (id)extraDictionary:(id)arg1 wasPrefilled:(BOOL)arg2;
+ (id)extraDictionary:(id)arg1 withNumberContacts:(int)arg2 andNumberFavoritesChosen:(int)arg3;
+ (id)extraDictionary:(id)arg1 withError:(id)arg2;
+ (id)extraDictionary:(id)arg1;
+ (id)stringForWaterfallAction:(unsigned int)arg1;
+ (id)stringForWaterfallStep:(unsigned int)arg1;
+ (void)logFinishRegistrationWithNumberContacts:(int)arg1 favoritesChosen:(int)arg2;
+ (void)logNameEnterSuccessWasPrefilled:(BOOL)arg1;
+ (void)logErrorAtStep:(unsigned int)arg1 withDescription:(id)arg2;
+ (void)logRegistrationStep:(unsigned int)arg1 actionTaken:(unsigned int)arg2;
@property(copy, nonatomic) NSString *event; // @synthesize event=_event;
@property(copy, nonatomic) NSString *module; // @synthesize module=_module;
@property(retain, nonatomic) NSDictionary *extras; // @synthesize extras=_extras;
- (void).cxx_destruct;

@end

