//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Request.h"

@interface APIRequest : Request
{
    BOOL _shouldSign;
}

+ (void)enumerateResultsWithRequest:(id)arg1 enumerationBlock:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (id)requestWithURL:(id)arg1;
+ (id)requestWithPath:(id)arg1;
@property(nonatomic) BOOL shouldSign; // @synthesize shouldSign=_shouldSign;

@end

