//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "RegistrationNavigationControllerDelegate.h"
#import "UIApplicationDelegate.h"

@class NSDictionary, UIWindow;

@interface AppDelegate : UIResponder <RegistrationNavigationControllerDelegate, UIApplicationDelegate>
{
    double _lastPushPromptTime;
    BOOL _blockAppLaunchUntilCrashReportingFinishes;
    UIWindow *_window;
    NSDictionary *_pushInfo;
}

@property(nonatomic) BOOL blockAppLaunchUntilCrashReportingFinishes; // @synthesize blockAppLaunchUntilCrashReportingFinishes=_blockAppLaunchUntilCrashReportingFinishes;
@property(retain, nonatomic) NSDictionary *pushInfo; // @synthesize pushInfo=_pushInfo;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)registrationNavigationControllerDidFinish:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)openCardsIfNecessary;
- (BOOL)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2;
- (void)stopApp;
- (void)userDidLogOut:(id)arg1;
- (void)onAPI401Received:(id)arg1;
- (void)handlePushIsDeniedByUser;
- (void)startAppFromRegistration:(BOOL)arg1;
- (void)showNeedVideoAccessAlert;
- (void)startApp;
- (void)fetchInstallUrl;
- (void)handleResignActive;
- (void)handleBecomeActive;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)performFinishedLaunchingWithLaunchOptions:(id)arg1;
- (void)initializeApp;
- (BOOL)isRecoveringFromCrash;
- (void)setCrashFlag;
- (void)clearCrashFile;
- (id)crashFilePath;
- (id)init;
- (void)dealloc;

@end

