//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SKStoreProductViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSObject<AppiraterDelegate>, NSString, UIAlertView;

@interface Appirater : NSObject <UIAlertViewDelegate, SKStoreProductViewControllerDelegate>
{
    UIAlertView *ratingAlert;
    BOOL _openInAppStore;
    NSObject<AppiraterDelegate> *_delegate;
    NSString *_alertTitle;
    NSString *_alertMessage;
    NSString *_alertCancelTitle;
    NSString *_alertRateTitle;
    NSString *_alertRateLaterTitle;
}

+ (void)closeModal;
+ (void)rateApp;
+ (id)topMostViewController:(id)arg1;
+ (id)getRootViewController;
+ (void)forceShowPrompt:(BOOL)arg1;
+ (void)tryToShowPrompt;
+ (void)showPrompt;
+ (void)userDidSignificantEvent:(BOOL)arg1;
+ (void)appEnteredForeground:(BOOL)arg1;
+ (void)appWillResignActive;
+ (void)appLaunched:(BOOL)arg1;
+ (void)appLaunched;
+ (id)sharedInstance;
+ (id)bundle;
+ (void)setAlwaysUseMainBundle:(BOOL)arg1;
+ (void)setModalOpen:(BOOL)arg1;
+ (void)setStatusBarStyle:(int)arg1;
+ (void)setOpenInAppStore:(BOOL)arg1;
+ (void)setUsesAnimation:(BOOL)arg1;
+ (void)setDelegate:(id)arg1;
+ (void)setDebug:(BOOL)arg1;
+ (void)setCustomAlertRateLaterButtonTitle:(id)arg1;
+ (void)setCustomAlertRateButtonTitle:(id)arg1;
+ (void)setCustomAlertCancelButtonTitle:(id)arg1;
+ (void)setCustomAlertMessage:(id)arg1;
+ (void)setCustomAlertTitle:(id)arg1;
+ (void)setTimeBeforeReminding:(double)arg1;
+ (void)setSignificantEventsUntilPrompt:(int)arg1;
+ (void)setUsesUntilPrompt:(int)arg1;
+ (void)setDaysUntilPrompt:(double)arg1;
+ (void)setAppId:(id)arg1;
@property(copy, nonatomic) NSString *alertRateLaterTitle; // @synthesize alertRateLaterTitle=_alertRateLaterTitle;
@property(copy, nonatomic) NSString *alertRateTitle; // @synthesize alertRateTitle=_alertRateTitle;
@property(copy, nonatomic) NSString *alertCancelTitle; // @synthesize alertCancelTitle=_alertCancelTitle;
@property(copy, nonatomic) NSString *alertMessage; // @synthesize alertMessage=_alertMessage;
@property(copy, nonatomic) NSString *alertTitle; // @synthesize alertTitle=_alertTitle;
@property(nonatomic) __weak NSObject<AppiraterDelegate> *delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL openInAppStore; // @synthesize openInAppStore=_openInAppStore;
@property(retain, nonatomic) UIAlertView *ratingAlert; // @synthesize ratingAlert;
- (void).cxx_destruct;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)showPromptWithChecks:(BOOL)arg1 displayRateLaterButton:(BOOL)arg2;
- (void)hideRatingAlert;
- (BOOL)userHasRatedCurrentVersion;
- (BOOL)userHasDeclinedToRate;
- (void)incrementSignificantEventAndRate:(BOOL)arg1;
- (void)incrementAndRate:(BOOL)arg1;
- (void)incrementSignificantEventCount;
- (void)incrementUseCount;
- (BOOL)ratingConditionsHaveBeenMet;
- (void)showRatingAlert;
- (void)showRatingAlert:(BOOL)arg1;
- (BOOL)connectedToNetwork;
- (id)init;
- (void)dealloc;

@end

