//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Authentication : NSObject
{
}

+ (id)facebookAuthInfo;
+ (void)logInWithFacebookWithCompletionHandler:(CDUnknownBlockType)arg1;
+ (void)validateApp;
+ (void)autoUpdate;
+ (void)crashOnBackground;
+ (void)logOut;
+ (void)updateCurrentUser:(id)arg1;
+ (id)currentUserID;
+ (id)currentUser;
+ (void)logInWithToken:(id)arg1 andUser:(id)arg2;
+ (id)signingKey;
+ (BOOL)isLoggedIn;
+ (id)attemptLoginWithResponse:(id)arg1;
+ (void)registerWithAuthenticationCode:(id)arg1 forCountryCode:(id)arg2 phoneNumber:(id)arg3 shortName:(id)arg4 fullName:(id)arg5 avatar:(id)arg6 avatarImageSource:(int)arg7 didPrefillName:(BOOL)arg8 completion:(CDUnknownBlockType)arg9 failure:(CDUnknownBlockType)arg10;
+ (void)passAccountCheckWithAuthenticationCode:(id)arg1 forCountryCode:(id)arg2 phoneNumber:(id)arg3 registrationType:(int)arg4 completion:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
+ (void)verifyAuthenticationCode:(id)arg1 forCountryCode:(id)arg2 phoneNumber:(id)arg3 completion:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
+ (void)requestAuthenticationCodeWithMethod:(int)arg1 countryCode:(id)arg2 phoneNumber:(id)arg3 completion:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
+ (id)deviceUDID;
+ (void)initialize;

@end

