//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NetworkImageView.h"

@interface AvatarImageView : NetworkImageView
{
    int _borderType;
    struct CGSize _imageSize;
}

@property struct CGSize imageSize; // @synthesize imageSize=_imageSize;
@property(nonatomic) int borderType; // @synthesize borderType=_borderType;
- (id)placeholderImage;
- (void)loadImageAtUrl:(id)arg1 clearPreviousImage:(BOOL)arg2;
- (id)prepareImage:(id)arg1 forUrl:(id)arg2;
- (int)maxImageEdge;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) BOOL highlighted;

@end

