//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "HeaderViewDelegate.h"
#import "RegistrationViewController.h"

@class CropView, CrystalBackgroundView, RegistrationNavigationController, UIButton, UIImage, UILabel;

@interface AvatarPickerViewController : BaseViewController <HeaderViewDelegate, RegistrationViewController>
{
    BOOL _registrationMode;
    id <AvatarPickerViewControllerDelegate> _delegate;
    CropView *_avatarImageView;
    UIButton *_doneButton;
    UIButton *_cancelButton;
    CrystalBackgroundView *_backgroundView;
    UILabel *_moveLabel;
    UIImage *_preselectedImage;
}

@property(retain, nonatomic) UIImage *preselectedImage; // @synthesize preselectedImage=_preselectedImage;
@property(retain, nonatomic) UILabel *moveLabel; // @synthesize moveLabel=_moveLabel;
@property(retain, nonatomic) CrystalBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) CropView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) BOOL registrationMode; // @synthesize registrationMode=_registrationMode;
@property(nonatomic) __weak id <AvatarPickerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)requiresOverlayView;
@property(readonly, nonatomic) int preferredGradientType;
- (void)onDoneTapped:(id)arg1;
- (void)onDoneTouched:(id)arg1;
- (void)onCancelTapped:(id)arg1;
- (void)onCancelTouched:(id)arg1;
- (void)setImage:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, nonatomic) RegistrationNavigationController *pp_navigationController;

@end

