//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "AvatarCameraViewControllerDelegate.h"
#import "AvatarPickerViewControllerDelegate.h"
#import "HeaderViewDelegate.h"
#import "RegistrationViewController.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSString, OptionButton, RegistrationNavigationController, UIImage, UIImageView, UILabel;

@interface AvatarViewController : BaseViewController <UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIGestureRecognizerDelegate, HeaderViewDelegate, AvatarCameraViewControllerDelegate, AvatarPickerViewControllerDelegate, RegistrationViewController>
{
    BOOL _didPrefillName;
    id <AvatarViewControllerDelegate> _delegate;
    NSString *_phoneNumber;
    NSString *_countryCode;
    NSString *_verificationCode;
    NSString *_shortName;
    NSString *_fullName;
    UIImage *_pendingAvatar;
    UILabel *_titleLabel;
    UIImageView *_avatarView;
    OptionButton *_importButton;
    OptionButton *_cameraButton;
}

@property(nonatomic) BOOL didPrefillName; // @synthesize didPrefillName=_didPrefillName;
@property(retain, nonatomic) OptionButton *cameraButton; // @synthesize cameraButton=_cameraButton;
@property(retain, nonatomic) OptionButton *importButton; // @synthesize importButton=_importButton;
@property(retain, nonatomic) UIImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImage *pendingAvatar; // @synthesize pendingAvatar=_pendingAvatar;
@property(copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(copy, nonatomic) NSString *shortName; // @synthesize shortName=_shortName;
@property(copy, nonatomic) NSString *verificationCode; // @synthesize verificationCode=_verificationCode;
@property(copy, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(retain, nonatomic) id <AvatarViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)avatarPickerViewController:(id)arg1 didChooseImage:(id)arg2;
- (void)avatarCameraViewController:(id)arg1 didCaptureImage:(id)arg2;
- (BOOL)headerViewShouldNavigateBackwards:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)makeRegistrationRequestWithAvatarImage:(id)arg1 fromSource:(int)arg2;
- (void)onCameraButtonTapped:(id)arg1;
- (void)onImportButtonTapped:(id)arg1;
- (void)viewDidLoad;
@property(readonly, nonatomic) int preferredGradientType;
- (BOOL)requiresOverlayView;
- (id)initWithPhoneNumber:(id)arg1 countryCode:(id)arg2 verificationCode:(id)arg3 shortName:(id)arg4 fullName:(id)arg5 pendingAvatar:(id)arg6 didPrefillName:(BOOL)arg7;

// Remaining properties
@property(readonly, nonatomic) RegistrationNavigationController *pp_navigationController;

@end

