//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "HeaderViewDelegate.h"
#import "RegistrationViewController.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class CaptureVideoPreviewLayer, CropView, CrystalBackgroundView, LMCaptureManager, RegistrationNavigationController, UIButton, UIImage, UILabel, UITapGestureRecognizer;

@interface AvatarCameraViewController : BaseViewController <UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIGestureRecognizerDelegate, HeaderViewDelegate, RegistrationViewController>
{
    BOOL _registrationMode;
    id <AvatarCameraViewControllerDelegate> _delegate;
    int _mode;
    UILabel *_titleLabel;
    CropView *_avatarImageView;
    UIButton *_captureButton;
    UIButton *_retakeButton;
    UIButton *_doneButton;
    UIButton *_cancelButton;
    LMCaptureManager *_captureManager;
    CaptureVideoPreviewLayer *_previewLayer;
    UITapGestureRecognizer *_tapRecognizer;
    UIImage *_pendingImage;
    CrystalBackgroundView *_backgroundView;
}

@property(retain, nonatomic) CrystalBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIImage *pendingImage; // @synthesize pendingImage=_pendingImage;
@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer=_tapRecognizer;
@property(retain, nonatomic) CaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer=_previewLayer;
@property(retain, nonatomic) LMCaptureManager *captureManager; // @synthesize captureManager=_captureManager;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) UIButton *retakeButton; // @synthesize retakeButton=_retakeButton;
@property(retain, nonatomic) UIButton *captureButton; // @synthesize captureButton=_captureButton;
@property(retain, nonatomic) CropView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) int mode; // @synthesize mode=_mode;
@property(nonatomic) BOOL registrationMode; // @synthesize registrationMode=_registrationMode;
@property(nonatomic) __weak id <AvatarCameraViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)requiresOverlayView;
@property(readonly, nonatomic) int preferredGradientType;
- (void)captureImage;
- (void)transitionToFinishMode;
- (void)transitionToCapureMode;
- (void)onRetakeButtonTapped:(id)arg1;
- (void)onCaptureButtonTouched:(id)arg1;
- (void)onCancelTouched:(id)arg1;
- (void)onCancelTapped:(id)arg1;
- (void)onDoneTapped:(id)arg1;
- (void)onDoneTouched:(id)arg1;
- (void)onTap:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, nonatomic) RegistrationNavigationController *pp_navigationController;

@end

