//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "AvatarCameraViewControllerDelegate.h"
#import "AvatarPickerViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class AvatarImageView;

@interface AvatarTableViewCell : UITableViewCell <UIActionSheetDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, AvatarCameraViewControllerDelegate, AvatarPickerViewControllerDelegate>
{
    id <AvatarTableViewCellDelegate> _delegate;
    AvatarImageView *_avatarImageView;
}

+ (float)defaultHeight;
@property(retain, nonatomic) AvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) __weak id <AvatarTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)avatarPickerViewController:(id)arg1 didChooseImage:(id)arg2;
- (void)avatarCameraViewController:(id)arg1 didCaptureImage:(id)arg2;
- (void)showCameraRoll;
- (void)showCamera;
- (void)actionSheet:(id)arg1 willDismissWithButtonIndex:(int)arg2;
- (void)onAvatarTapped:(id)arg1;
- (void)setImageURL:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

