//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AvatarPickerViewController, UIImage;

@protocol AvatarPickerViewControllerDelegate <NSObject>
- (void)avatarPickerViewController:(AvatarPickerViewController *)arg1 didChooseImage:(UIImage *)arg2;
@end

