//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Request.h"

@class NSString;

@interface BackgroundUploadAPIRequest : Request
{
    BOOL _shouldSign;
    NSString *_uuid;
}

+ (id)requestWithPath:(id)arg1 andUuid:(id)arg2;
@property(nonatomic) BOOL shouldSign; // @synthesize shouldSign=_shouldSign;
@property(readonly, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (int)priority;

@end

