//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "HeaderViewDelegate.h"

@class HeaderView, NavigationController;

@interface BaseViewController : UIViewController <HeaderViewDelegate>
{
    HeaderView *_headerView;
}

@property(retain, nonatomic) HeaderView *headerView; // @synthesize headerView=_headerView;
- (void).cxx_destruct;
- (void)didMoveToParentViewController:(id)arg1;
@property(readonly, nonatomic) NavigationController *pp_navigationController;
- (void)viewDidLoad;

@end

