//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Blocker : NSObject
{
}

+ (void)sendUnblockUserRequestWithUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)sendBlockUserRequestWithUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)unblockUser:(id)arg1 confirm:(BOOL)arg2 completion:(CDUnknownBlockType)arg3 fromRecents:(BOOL)arg4;
+ (void)unblockUser:(id)arg1 confirm:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)blockUser:(id)arg1 confirm:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)fetchBlockedUsersWithCompletion:(CDUnknownBlockType)arg1;

@end

