//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface CALayer (PPWiggle)
- (BOOL)pp_isShaking;
- (void)pp_shakeLayer;
- (BOOL)pp_isWiggling;
- (void)pp_stopWiggling;
- (void)pp_startWiggling;
@end

