//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CaptureManagerHelper : NSObject
{
}

+ (struct CGAffineTransform)transformForInterfaceOrientation:(int)arg1 devicePosition:(int)arg2;
+ (id)imageWithSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 devicePosition:(int)arg2;
+ (id)flatImageOfSize:(struct CGSize)arg1 color:(id)arg2;

@end

