//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CaptureViewController;

@protocol CaptureViewControllerDelegate <NSObject>
- (void)captureControllerDidReachRecordingTimeLimit:(CaptureViewController *)arg1;
- (void)captureControllerEndRecording:(CaptureViewController *)arg1;
- (void)captureControllerDidStartRecording:(CaptureViewController *)arg1;
- (void)captureControllerDidEndDrawing:(CaptureViewController *)arg1;
- (void)captureControllerDidBeginDrawing:(CaptureViewController *)arg1;
- (void)captureControllerDidEndTextEditing:(CaptureViewController *)arg1;
- (void)captureControllerDidBeginTextEditing:(CaptureViewController *)arg1;

@optional
- (void)captureViewControllerWantsCameraUnpause:(CaptureViewController *)arg1;
@end

