//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IncomingMessage, UIButton;

@interface CardView : UIView
{
    id <CardViewDelegate> _delegate;
    IncomingMessage *_message;
    UIView *_contentView;
    UIButton *_dismissButton;
    UIView *_overlay;
}

@property(retain, nonatomic) UIView *overlay; // @synthesize overlay=_overlay;
@property(retain, nonatomic) UIButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) IncomingMessage *message; // @synthesize message=_message;
@property(nonatomic) __weak id <CardViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleExitingBlur;
- (void)handleEnteringBlur;
- (void)handleBeingDismissed;
- (void)handleBecomingFrontmostCard;
- (void)onDismissTapped:(id)arg1;
- (void)addSubview:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

