//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSHashTable, UIPanGestureRecognizer;

@interface CardStackView : UIView <UIGestureRecognizerDelegate>
{
    BOOL _gesturesDisabled;
    BOOL _isExpanded;
    id <CardStackViewDataSource> _dataSource;
    id <CardStackViewDelegate> _delegate;
    UIView *_frontCard;
    UIView *_backCard;
    UIPanGestureRecognizer *_panRecognizer;
    float _previousAngle;
    float _cumulativeAngle;
    float _angleDampiningAmount;
    NSHashTable *_dismissedViews;
    struct CGPoint _initialTranslation;
    struct CGPoint _initialTouchPoint;
}

+ (void)scheduleBlockAfterDismissAnimationsComplete:(CDUnknownBlockType)arg1;
+ (id)scheduledCompletionBlocks;
+ (void)dismissAnimationDidFinish;
+ (void)dismissAnimationDidStart;
@property(retain, nonatomic) NSHashTable *dismissedViews; // @synthesize dismissedViews=_dismissedViews;
@property(nonatomic) float angleDampiningAmount; // @synthesize angleDampiningAmount=_angleDampiningAmount;
@property(nonatomic) float cumulativeAngle; // @synthesize cumulativeAngle=_cumulativeAngle;
@property(nonatomic) float previousAngle; // @synthesize previousAngle=_previousAngle;
@property(nonatomic) struct CGPoint initialTouchPoint; // @synthesize initialTouchPoint=_initialTouchPoint;
@property(nonatomic) struct CGPoint initialTranslation; // @synthesize initialTranslation=_initialTranslation;
@property(retain, nonatomic) UIPanGestureRecognizer *panRecognizer; // @synthesize panRecognizer=_panRecognizer;
@property(retain, nonatomic) UIView *backCard; // @synthesize backCard=_backCard;
@property(retain, nonatomic) UIView *frontCard; // @synthesize frontCard=_frontCard;
@property(readonly, nonatomic) BOOL isExpanded; // @synthesize isExpanded=_isExpanded;
@property(nonatomic) BOOL gesturesDisabled; // @synthesize gesturesDisabled=_gesturesDisabled;
@property(nonatomic) __weak id <CardStackViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <CardStackViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)stopAnimations;
- (void)popTopItem;
- (void)reloadData;
- (void)reloadDataIfNecessary;
- (void)setFrame:(struct CGRect)arg1;
- (void)onPan:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)loadBackCard;
- (id)initWithFrame:(struct CGRect)arg1;

@end

