//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CAEAGLLayer.h"

@interface CIImageLayer : CAEAGLLayer
{
    unsigned int _framebuffer;
    unsigned int _renderbuffer;
    struct CGAffineTransform _videoTransform;
    struct CGSize _contentSize;
}

+ (void)makeCurrent;
+ (id)ciContext;
+ (id)eaglContext;
- (void)drawImage:(id)arg1;
- (id)init;
- (void)dealloc;

@end

