//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIView;

@interface ClearTableViewCell : UITableViewCell
{
    int _actionType;
    UIView *_bottomBorderView;
    int _style;
}

+ (float)heightWithDetailText:(id)arg1 withAccessory:(BOOL)arg2;
+ (float)detailTextLabelWidthWithAccessory:(BOOL)arg1;
+ (id)detailTextLabelFont;
+ (float)defaultHeight;
@property int style; // @synthesize style=_style;
@property(retain, nonatomic) UIView *bottomBorderView; // @synthesize bottomBorderView=_bottomBorderView;
@property(nonatomic) int actionType; // @synthesize actionType=_actionType;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)prepareForReuse;
- (void)setAccessoryType:(int)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

