//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSArray, UIColor, UIPanGestureRecognizer;

@interface ColorPicker : UIControl
{
    UIColor *_color;
    struct CGRect *_slices;
    NSArray *_colors;
    UIPanGestureRecognizer *_panRecognizer;
    struct CGPoint _colorLocation;
}

@property(retain, nonatomic) UIPanGestureRecognizer *panRecognizer; // @synthesize panRecognizer=_panRecognizer;
@property(retain, nonatomic) NSArray *colors; // @synthesize colors=_colors;
@property(nonatomic) struct CGRect *slices; // @synthesize slices=_slices;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) struct CGPoint colorLocation; // @synthesize colorLocation=_colorLocation;
- (void).cxx_destruct;
- (BOOL)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (BOOL)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)buildUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

