//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ContactsPromptViewControllerDelegate.h"
#import "InviteViewControllerDelegate.h"
#import "JRModelManagerSubscriber.h"
#import "UserSearchViewControllerDelegate.h"

@class HeaderView, HeaderViewButton, InviteViewController, NSArray, NSString, UITableView, UIView, UserSearchViewController;

@interface ContactsViewController : UIViewController <JRModelManagerSubscriber, UserSearchViewControllerDelegate, InviteViewControllerDelegate, ContactsPromptViewControllerDelegate>
{
    BOOL _ignoreRecentsChanges;
    id <ContactsViewControllerDelegate> _delegate;
    NSArray *_recents;
    NSArray *_users;
    NSArray *_nearbyPeers;
    NSArray *_contactsToInvite;
    HeaderView *_headerView;
    HeaderViewButton *_doneButton;
    UITableView *_tableView;
    UserSearchViewController *_searchController;
    UIView *_searchControllerOverlay;
    InviteViewController *_inviteController;
    UIView *_inviteControllerOverlay;
    NSString *_usersRequestId;
    NSString *_recentsRequestId;
}

@property(nonatomic) BOOL ignoreRecentsChanges; // @synthesize ignoreRecentsChanges=_ignoreRecentsChanges;
@property(copy, nonatomic) NSString *recentsRequestId; // @synthesize recentsRequestId=_recentsRequestId;
@property(copy, nonatomic) NSString *usersRequestId; // @synthesize usersRequestId=_usersRequestId;
@property(retain, nonatomic) UIView *inviteControllerOverlay; // @synthesize inviteControllerOverlay=_inviteControllerOverlay;
@property(retain, nonatomic) InviteViewController *inviteController; // @synthesize inviteController=_inviteController;
@property(retain, nonatomic) UIView *searchControllerOverlay; // @synthesize searchControllerOverlay=_searchControllerOverlay;
@property(retain, nonatomic) UserSearchViewController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) HeaderViewButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) HeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSArray *contactsToInvite; // @synthesize contactsToInvite=_contactsToInvite;
@property(retain, nonatomic) NSArray *nearbyPeers; // @synthesize nearbyPeers=_nearbyPeers;
@property(retain, nonatomic) NSArray *users; // @synthesize users=_users;
@property(retain, nonatomic) NSArray *recents; // @synthesize recents=_recents;
@property(nonatomic) __weak id <ContactsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)logFinishRegistration;
- (void)resultsUpdatedForRequest:(id)arg1 results:(id)arg2 changes:(id)arg3;
- (void)dismissInviteViewController:(id)arg1;
- (void)inviteViewControllerDidTapCancel:(id)arg1;
- (void)dismissUserSearchViewController:(id)arg1;
- (void)userSearchViewControllerDidTapCancel:(id)arg1;
- (void)userSearchViewController:(id)arg1 didSelectUser:(id)arg2;
- (void)contactsPromptViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)enterInviteMode;
- (id)filterInvalidResultsFromResults:(id)arg1;
- (void)enterSearchMode;
- (int)numberOfFavorites;
- (void)updateDoneButtonState;
- (void)onSearchButtonTapped:(id)arg1;
- (void)onDoneButtonTapped:(id)arg1;
- (void)onInviteBackgroundTapped:(id)arg1;
- (void)onBackgroundTapped:(id)arg1;
- (void)sendDoneDelegateCallback;
- (id)doneButtonTitle;
- (void)handleHasContactsAccess;
- (void)handleDidEnterSearch;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)showDescriptionText;
- (BOOL)shouldShowContactsToInvite;
- (BOOL)showEnableNearby;
- (void)showContactsPrompt;
- (void)onKeyboardWillHide:(id)arg1;
- (void)onKeyboardWillShow:(id)arg1;
- (void)onPeerListChanged:(id)arg1;
- (void)updateForKeyboardFrame:(struct CGRect)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

@end

