//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JRModelManager.h"

#import "JRModelManagerSubscriber.h"

@class NSString;

@interface ContentModelManager : JRModelManager <JRModelManagerSubscriber>
{
    BOOL _hasCachedFavoritesCount;
    int _cachedFavoritesCount;
    NSString *_favoritesRequestId;
}

+ (id)sharedInstance;
@property(copy) NSString *favoritesRequestId; // @synthesize favoritesRequestId=_favoritesRequestId;
@property(nonatomic) BOOL hasCachedFavoritesCount; // @synthesize hasCachedFavoritesCount=_hasCachedFavoritesCount;
- (void).cxx_destruct;
- (void)resultsUpdatedForRequest:(id)arg1 results:(id)arg2 changes:(id)arg3;
- (void)rebuildSortOrderForFavoritesUsingUserList:(id)arg1;
@property int cachedFavoritesCount; // @synthesize cachedFavoritesCount=_cachedFavoritesCount;
- (id)favorites;
- (id)messageWithRemoteId:(id)arg1;
- (id)debugString;
- (void)forceSave;
- (void)performBatchOperation:(CDUnknownBlockType)arg1;
- (void)performBatchOperationAndWait:(CDUnknownBlockType)arg1;
- (void)flushAllStoredData;
- (void)cancelSubscriptionForSubscriber:(id)arg1;
- (void)addNonFavoriteRecentSendersSubscriber:(id)arg1 requestCallback:(CDUnknownBlockType)arg2;
- (void)addRecentSendersSubscriber:(id)arg1;
- (void)addUsersSubscriber:(id)arg1 requestCallback:(CDUnknownBlockType)arg2;
- (void)addBlockedUsersSubscriber:(id)arg1;
- (void)addFavoriteUsersSubscriber:(id)arg1;
- (void)addFavoriteUsersSubscriber:(id)arg1 requestCallback:(CDUnknownBlockType)arg2;
- (void)addUndownloadedMessagesSubscriber:(id)arg1;
- (void)addDeletedMessagesSubscriber:(id)arg1;
- (void)addOutgoingMessagesSubscriber:(id)arg1;
- (void)addDownloadedMessageListSubscriber:(id)arg1;
- (id)favoritesSortDescriptors;
- (id)favoriteUsersPredicate;
- (id)downloadedMessageListPredicate;
- (id)receivedMessageListPredicate;
- (Class)_modelClassForManagedObject:(id)arg1;
- (id)init;
- (id)allRepliedToMessages;
- (id)allMessageReplies;
- (id)allUsers;
- (id)messageWithRemoteID:(id)arg1;
- (void)dumpAllDataToConsole;
- (void)markMessageWithUuidAsUploaded:(id)arg1 withRemoteID:(id)arg2;
- (id)allOutgoingMessages;
- (void)video:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (BOOL)hasLastSentMessageToSave;
- (void)saveLastMessage;
- (void)replyToMessage:(id)arg1 withVideo:(id)arg2 text:(id)arg3 textYOffset:(float)arg4;
- (void)replyToMessage:(id)arg1 withImage:(id)arg2 text:(id)arg3 textYOffset:(float)arg4;
- (void)replyToMessage:(id)arg1 withText:(id)arg2 textYOffset:(float)arg3;
- (void)sendVideo:(id)arg1 text:(id)arg2 textYOffset:(float)arg3 toUser:(id)arg4 existingMessageID:(id)arg5;
- (void)sendVideo:(id)arg1 text:(id)arg2 textYOffset:(float)arg3 toUser:(id)arg4;
- (void)sendImage:(id)arg1 text:(id)arg2 textYOffset:(float)arg3 toUser:(id)arg4 existingMessageID:(id)arg5;
- (void)sendImage:(id)arg1 text:(id)arg2 textYOffset:(float)arg3 toUser:(id)arg4;
- (void)saveLastSendWithVideoUrl:(id)arg1;
- (void)saveLastSendWithImage:(id)arg1;
- (id)allUsersIds;
- (id)userWithID:(id)arg1;
- (void)removeDeadUserWithUserID:(id)arg1;
- (void)removeStaleMessagesWithRemoteIDs:(id)arg1;
- (BOOL)addNewSenderMessageWithRemoteID:(id)arg1 userRemoteID:(id)arg2 sentDate:(id)arg3 outMessage:(id *)arg4;
- (BOOL)addContactJoinedMessageWithRemoteID:(id)arg1 userRemoteID:(id)arg2 sentDate:(id)arg3 outMessage:(id *)arg4;
- (void)updateMessageWithRemoteID:(id)arg1 type:(int)arg2 text:(id)arg3 textYOffset:(float)arg4 previousText:(id)arg5 previousTextYOffset:(float)arg6 senderRemoteID:(id)arg7 mediaURL:(id)arg8 isReply:(BOOL)arg9 sentDate:(id)arg10;
- (BOOL)addMessageWithRemoteID:(id)arg1 type:(int)arg2 text:(id)arg3 textYOffset:(float)arg4 previousText:(id)arg5 previousTextYOffset:(float)arg6 senderRemoteID:(id)arg7 mediaURL:(id)arg8 isReply:(BOOL)arg9 sentDate:(id)arg10 outMessage:(id *)arg11;
- (void)updateUserWithRemoteID:(id)arg1 imageUrl:(id)arg2 shortName:(id)arg3 fullName:(id)arg4 countryCode:(id)arg5 favorite:(int)arg6 blocked:(int)arg7 nationalNumber:(id)arg8 lastContactedDate:(id)arg9 inAddressBook:(BOOL)arg10;
- (id)addUserWithRemoteID:(id)arg1 imageUrl:(id)arg2 shortName:(id)arg3 fullName:(id)arg4 countryCode:(id)arg5 nationalNumber:(id)arg6 lastContactedDate:(id)arg7 favorite:(int)arg8 blocked:(int)arg9 inAddressBook:(BOOL)arg10;
- (id)allUnreadMessages;
- (id)allMessages;
- (void)markMessageWithRemoteIDAsDeleted:(id)arg1;
- (id)allDeletedMessages;
- (id)allUndownloadedMessages;
- (void)deleteMessagesForBlockedUserWithId:(id)arg1;

@end

