//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CardView.h"

#import "NetworkImageViewDelegate.h"

@class AvatarImageView, CrystalBackgroundView, IncomingMessage, UIButton, UIImageView, UILabel;

@interface ContactCardView : CardView <NetworkImageViewDelegate>
{
    BOOL _messageIsFromContactInAddressBook;
    IncomingMessage *_message;
    UIImageView *_blurredImageView;
    CrystalBackgroundView *_backgroundView;
    AvatarImageView *_avatarView;
    UILabel *_titleLabel;
    UIButton *_addToFavoritesButton;
    UILabel *_descriptionLabel;
    UILabel *_swipeToDismissLabel;
}

@property(nonatomic, getter=isMessageIsFromContactInAddressBook) BOOL messageIsFromContactInAddressBook; // @synthesize messageIsFromContactInAddressBook=_messageIsFromContactInAddressBook;
@property(retain, nonatomic) UILabel *swipeToDismissLabel; // @synthesize swipeToDismissLabel=_swipeToDismissLabel;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UIButton *addToFavoritesButton; // @synthesize addToFavoritesButton=_addToFavoritesButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) AvatarImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) CrystalBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIImageView *blurredImageView; // @synthesize blurredImageView=_blurredImageView;
@property(retain, nonatomic) IncomingMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)onFavoriteButtonTapped:(id)arg1;
- (id)detailText;
- (id)reasonText;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) __weak id <ContactCardViewDelegate> delegate;

@end

