//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface ContactsPromptViewController : UIViewController
{
    id <ContactsPromptViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <ContactsPromptViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onContinueButtonTapped:(id)arg1;
- (id)titleString;
- (void)viewDidLoad;
- (id)init;

@end

