//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CardViewDelegate.h"

@class ContactCardView;

@protocol ContactCardViewDelegate <CardViewDelegate>
- (void)contactCardViewDidTryToFavorite:(ContactCardView *)arg1;
- (void)contactCardViewDidFavorite:(ContactCardView *)arg1;
@end

