//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Country, CountryPickerViewController;

@protocol CountryPickerViewControllerDelegate <NSObject>
- (void)countryPicker:(CountryPickerViewController *)arg1 didPickCountry:(Country *)arg2;

@optional
- (void)countryPickerDidCancel:(CountryPickerViewController *)arg1;
@end

