//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class UIView;

@interface CropView : UIScrollView <UIScrollViewDelegate>
{
    struct UIEdgeInsets _touchPadding;
}

@property(nonatomic) struct UIEdgeInsets touchPadding; // @synthesize touchPadding=_touchPadding;
- (id)viewForZoomingInScrollView:(id)arg1;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)onDoubleTap:(id)arg1;
- (void)resetCropRectAnimated:(BOOL)arg1;
@property(nonatomic) struct CGRect cropRect;
- (void)setCropRect:(struct CGRect)arg1 animated:(BOOL)arg2;
@property(nonatomic) float maximumZoom;
@property(nonatomic, getter=isZoomEnabled) BOOL zoomEnabled;
@property(retain, nonatomic) UIView *contentView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

