//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class UIColor;

@interface CrystalBackgroundView : UIImageView
{
    float _transitionDuration;
    UIColor *_blurredRegionTintColor;
    UIImageView *_blurredView;
    int _gradientType;
}

@property(nonatomic) int gradientType; // @synthesize gradientType=_gradientType;
@property(retain, nonatomic) UIImageView *blurredView; // @synthesize blurredView=_blurredView;
@property(retain, nonatomic) UIColor *blurredRegionTintColor; // @synthesize blurredRegionTintColor=_blurredRegionTintColor;
@property(nonatomic) float transitionDuration; // @synthesize transitionDuration=_transitionDuration;
- (void).cxx_destruct;
- (id)blurredImageWithImage:(id)arg1;
@property(nonatomic) struct CGRect blurredRegion;
- (void)moveToGradientType:(int)arg1 patternAlpha:(float)arg2 animated:(BOOL)arg3;
- (void)moveToGradientType:(int)arg1 animated:(BOOL)arg2;
- (id)colorsForGradientType:(int)arg1;

@end

