//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class FavoritesListener, MessagesListener, OutgoingMessagesListener, UILabel, UserListener;

@interface DatabaseDebugViewController : UIViewController
{
    FavoritesListener *_favorites;
    UserListener *_users;
    MessagesListener *_messages;
    OutgoingMessagesListener *_outgoing;
    UILabel *_infoLabel;
}

@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) OutgoingMessagesListener *outgoing; // @synthesize outgoing=_outgoing;
@property(retain, nonatomic) MessagesListener *messages; // @synthesize messages=_messages;
@property(retain, nonatomic) UserListener *users; // @synthesize users=_users;
@property(retain, nonatomic) FavoritesListener *favorites; // @synthesize favorites=_favorites;
- (void).cxx_destruct;
- (void)updateUINote:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

