//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCache.h"

@interface DecodedImageCache : NSCache
{
}

+ (void)setImage:(id)arg1 forKey:(id)arg2;
+ (id)imageForKey:(id)arg1;
+ (id)cache;
+ (void)setBlurredImage:(id)arg1 forMessage:(id)arg2;
+ (id)blurredImageForMessage:(id)arg1;
+ (void)setImage:(id)arg1 forMessage:(id)arg2;
+ (id)imageForMessage:(id)arg1;

@end

