//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "UITextFieldDelegate.h"

@class NSDictionary, NSMutableArray, NSString, PaddedTextField, UILabel;

@interface DigitTextField : UIControl <UITextFieldDelegate>
{
    NSMutableArray *_carretViews;
    PaddedTextField *_textField;
    UILabel *_dashLabel;
    unsigned int _blinkPosition;
}

@property(nonatomic) unsigned int blinkPosition; // @synthesize blinkPosition=_blinkPosition;
@property(retain, nonatomic) UILabel *dashLabel; // @synthesize dashLabel=_dashLabel;
@property(retain, nonatomic) PaddedTextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) NSMutableArray *carretViews; // @synthesize carretViews=_carretViews;
- (void).cxx_destruct;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (id)verificationNumberFromText:(id)arg1;
- (void)onTextFieldChanged;
@property(copy, nonatomic) NSString *text;
- (BOOL)becomeFirstResponder;
@property(copy, nonatomic) NSDictionary *textAttributes;
- (void)layoutSubviews;

@end

