//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, NSMutableData, UIColor;

@interface DrawingCanvasView : UIView
{
    BOOL _editable;
    UIColor *_lineColor;
    NSMutableData *_points;
    NSMutableArray *_lines;
    NSMutableArray *_lineColors;
    struct CGPoint _lastPoint;
}

@property(retain, nonatomic) NSMutableArray *lineColors; // @synthesize lineColors=_lineColors;
@property(retain, nonatomic) NSMutableArray *lines; // @synthesize lines=_lines;
@property(retain, nonatomic) NSMutableData *points; // @synthesize points=_points;
@property(nonatomic) struct CGPoint lastPoint; // @synthesize lastPoint=_lastPoint;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) BOOL editable; // @synthesize editable=_editable;
- (void).cxx_destruct;
- (id)lineImageWithSize:(struct CGSize)arg1;
- (id)renderLinesOnImage:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)renderLine:(id)arg1 withColor:(id)arg2 scale:(float)arg3;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)recordPoint:(struct CGPoint)arg1;
- (struct CGRect)rectForPoint:(struct CGPoint)arg1;
- (void)clear;
- (void)undoLastLine;
- (id)initWithFrame:(struct CGRect)arg1;

@end

