//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "POPAnimationDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSMutableArray, TouchGestureRecognizer, UILongPressGestureRecognizer, UIScrollView, UITapGestureRecognizer;

@interface DynamicCollectionView : UIView <UIScrollViewDelegate, UIGestureRecognizerDelegate, POPAnimationDelegate>
{
    BOOL _isPaging;
    id <IGDynamicCollectionViewDelegate> _delegate;
    id <IGDynamicCollectionViewDataSource> _dataSource;
    float _itemSpacing;
    float _pagePadding;
    int _currentPage;
    UIScrollView *_contentView;
    UILongPressGestureRecognizer *_touchRecognizer;
    TouchGestureRecognizer *_velocityRecognizer;
    UITapGestureRecognizer *_tapRecognizer;
    NSMutableArray *_views;
    NSMutableArray *_viewCenters;
    float _maxWidth;
    UIView *_trackingView;
    int _trackingViewStartIndex;
    struct CGPoint _gestureStartLocation;
    struct CGPoint _trackingViewStartLocation;
}

@property(nonatomic) BOOL isPaging; // @synthesize isPaging=_isPaging;
@property(nonatomic) struct CGPoint trackingViewStartLocation; // @synthesize trackingViewStartLocation=_trackingViewStartLocation;
@property(nonatomic) int trackingViewStartIndex; // @synthesize trackingViewStartIndex=_trackingViewStartIndex;
@property(retain, nonatomic) UIView *trackingView; // @synthesize trackingView=_trackingView;
@property(nonatomic) float maxWidth; // @synthesize maxWidth=_maxWidth;
@property(retain, nonatomic) NSMutableArray *viewCenters; // @synthesize viewCenters=_viewCenters;
@property(nonatomic) struct CGPoint gestureStartLocation; // @synthesize gestureStartLocation=_gestureStartLocation;
@property(retain, nonatomic) NSMutableArray *views; // @synthesize views=_views;
@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer=_tapRecognizer;
@property(retain, nonatomic) TouchGestureRecognizer *velocityRecognizer; // @synthesize velocityRecognizer=_velocityRecognizer;
@property(retain, nonatomic) UILongPressGestureRecognizer *touchRecognizer; // @synthesize touchRecognizer=_touchRecognizer;
@property(retain, nonatomic) UIScrollView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) int currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) float pagePadding; // @synthesize pagePadding=_pagePadding;
@property(nonatomic) float itemSpacing; // @synthesize itemSpacing=_itemSpacing;
@property(nonatomic) __weak id <IGDynamicCollectionViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <IGDynamicCollectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)applyAttachmentsBlockAnimationForViews:(id)arg1;
- (void)applyAttachments;
- (void)stopAnimationsForView:(id)arg1;
- (void)moveView:(id)arg1 toPoint:(struct CGPoint)arg2 withVelocity:(struct CGPoint)arg3;
- (void)scaleToValue:(float)arg1 withVelocity:(float)arg2 forView:(id)arg3;
- (void)scaleBounceView:(id)arg1;
- (int)numberOfPagesForContentSize:(float)arg1;
@property(readonly, nonatomic) int numberOfPages;
- (id)viewForPoint:(struct CGPoint)arg1;
- (void)cancelTransformSprings;
- (void)cancelCenterSprings;
- (id)centerSpringAnimationForView:(id)arg1;
- (id)transformSpringAnimationForView:(id)arg1;
- (void)scrollToIndex:(int)arg1;
- (void)scrollToPage:(int)arg1 slowAnimation:(BOOL)arg2;
- (void)scrollToPage:(int)arg1;
- (void)pageToIndex:(int)arg1;
- (void)touch:(id)arg1;
- (void)pan:(id)arg1;
- (void)tap:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)updateForTouchRecognizerChange;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollToLastItemAnimated:(BOOL)arg1;
- (void)reloadDataAnimated:(BOOL)arg1;
@property(nonatomic) BOOL alwaysBounceHorizontal;
- (void)layoutSubviews;
@property(readonly, nonatomic) NSArray *allViews;
@property(readonly, nonatomic) NSArray *visibleViews;
@property(readonly, nonatomic) struct CGSize contentSize;
- (void)setUpSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

