//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TableViewController.h"

#import "HeaderViewDelegate.h"
#import "TextFieldTableViewCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class HeaderViewButton, NSString, UIActivityIndicatorView;

@interface EditNameViewController : TableViewController <UITableViewDataSource, UITableViewDelegate, HeaderViewDelegate, TextFieldTableViewCellDelegate>
{
    BOOL _useFullNameLocalUI;
    id <EditNameViewControllerDelegate> _delegate;
    HeaderViewButton *_saveButton;
    UIActivityIndicatorView *_spinner;
    NSString *_savedFirstTextFieldText;
    NSString *_savedSecondTextFieldText;
    NSString *_shortName;
    NSString *_lastNameGuess;
    NSString *_fullName;
}

@property(nonatomic) BOOL useFullNameLocalUI; // @synthesize useFullNameLocalUI=_useFullNameLocalUI;
@property(copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(copy, nonatomic) NSString *lastNameGuess; // @synthesize lastNameGuess=_lastNameGuess;
@property(copy, nonatomic) NSString *shortName; // @synthesize shortName=_shortName;
@property(copy, nonatomic) NSString *savedSecondTextFieldText; // @synthesize savedSecondTextFieldText=_savedSecondTextFieldText;
@property(copy, nonatomic) NSString *savedFirstTextFieldText; // @synthesize savedFirstTextFieldText=_savedFirstTextFieldText;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) HeaderViewButton *saveButton; // @synthesize saveButton=_saveButton;
@property(nonatomic) __weak id <EditNameViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)performSave;
- (void)onSaveButtonTapped:(id)arg1;
- (void)saveIfNecessary;
- (BOOL)textFieldCell:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldCell:(id)arg1 didChangeText:(id)arg2;
- (void)textFieldCellDidTapReturn:(id)arg1;
- (BOOL)headerViewShouldNavigateBackwards:(id)arg1;
- (void)updateSaveButtonVisibility;
- (BOOL)hasChanges;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)setUpTableView;
- (void)setUpHeaderView;
- (BOOL)getFirstName:(id *)arg1 andLastName:(id *)arg2 fromFullName:(id)arg3 andShortName:(id)arg4;
- (id)trimString:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (id)init;

@end

