//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FacebookAuthInfo : NSObject
{
    BOOL _isEmployee;
    NSString *_userId;
    NSString *_username;
    NSString *_accessToken;
}

@property(nonatomic) BOOL isEmployee; // @synthesize isEmployee=_isEmployee;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;

@end

