//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JRModelManagerSubscriber.h"

@class NSArray;

@interface FavoritesListener : NSObject <JRModelManagerSubscriber>
{
    NSArray *_favorites;
}

@property(copy) NSArray *favorites; // @synthesize favorites=_favorites;
- (void).cxx_destruct;
- (void)resultsUpdatedForRequest:(id)arg1 results:(id)arg2 changes:(id)arg3;

@end

