//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, Reachability;

@interface Fetcher : NSObject
{
    BOOL _disabled;
    BOOL _hasFetchedUsers;
    Reachability *_reachability;
    NSMutableArray *_userFetchCompletionBlocks;
    int _fetchingUsersCount;
}

+ (void)setDisabled:(BOOL)arg1;
+ (void)fetchMessageWithRemoteID:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)performAfterUsersFetched:(CDUnknownBlockType)arg1;
+ (BOOL)hasFetchedUsers;
+ (id)sharedInstance;
+ (void)start;
@property(nonatomic) int fetchingUsersCount; // @synthesize fetchingUsersCount=_fetchingUsersCount;
@property(nonatomic) BOOL hasFetchedUsers; // @synthesize hasFetchedUsers=_hasFetchedUsers;
@property(retain, nonatomic) NSMutableArray *userFetchCompletionBlocks; // @synthesize userFetchCompletionBlocks=_userFetchCompletionBlocks;
@property(retain, nonatomic) Reachability *reachability; // @synthesize reachability=_reachability;
@property(nonatomic) BOOL disabled; // @synthesize disabled=_disabled;
- (void).cxx_destruct;
- (void)performAfterUsersFetched:(CDUnknownBlockType)arg1;
- (void)fetchUsers;
- (void)trimDeadUsersIfNeededUsingKnownRemoteUserIDs:(id)arg1;
- (void)fetchMessages;
- (void)fetchMessageWithRemoteID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)onUserDidLogOut:(id)arg1;
- (void)onContactSyncFinished:(id)arg1;
- (void)applicationBecameActive:(id)arg1;
- (id)init;
- (void)dealloc;

@end

