//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FileManager : NSObject
{
}

+ (void)deleteAllFiles;
+ (BOOL)deleteFileWithUUID:(id)arg1 error:(id *)arg2;
+ (BOOL)deleteFileForMediaURL:(id)arg1 error:(id *)arg2;
+ (BOOL)addFileWithData:(id)arg1 forMediaURL:(id)arg2 error:(id *)arg3;
+ (BOOL)addFileWithData:(id)arg1 forUUID:(id)arg2 error:(id *)arg3;
+ (BOOL)addFileWithExistingPath:(id)arg1 forMediaURL:(id)arg2 error:(id *)arg3;
+ (BOOL)addFileWithExistingPath:(id)arg1 forUUID:(id)arg2 error:(id *)arg3;
+ (id)dataForUUID:(id)arg1;
+ (id)filePathForMediaURL:(id)arg1;
+ (id)filePathForUUID:(id)arg1;
+ (id)directoryPath;
+ (int)fileCount;
+ (void)initialize;

@end

