//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MultiPart.h"

@class NSData, NSString;

@interface FileMultiPart : MultiPart
{
    NSData *_data;
    NSString *_path;
    NSString *_name;
    NSString *_mimeType;
    NSString *_filename;
}

+ (id)multipartWithPath:(id)arg1 name:(id)arg2 filename:(id)arg3 mimeType:(id)arg4;
+ (id)multipartWithData:(id)arg1 name:(id)arg2 filename:(id)arg3 mimeType:(id)arg4;
@property(copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
@property(copy, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)writePartDataToFileHandler:(id)arg1;
- (id)partData;

@end

