//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface FormattedLabel : UILabel
{
    float _lineHeight;
}

@property(nonatomic) float lineHeight; // @synthesize lineHeight=_lineHeight;
- (void)updateText;
- (void)setText:(id)arg1;
- (void)setFont:(id)arg1;
- (void)setTextAlignment:(int)arg1;

@end

