//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GTMLogFilter.h"

@class NSIndexSet;

@interface GTMLogAllowedLevelFilter : NSObject <GTMLogFilter>
{
    NSIndexSet *allowedLevels_;
}

- (BOOL)filterAllowsMessage:(id)arg1 level:(int)arg2;
- (void)dealloc;
- (id)init;
- (id)initWithAllowedLevels:(id)arg1;

@end

