//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSLayoutConstraint, NSString, NavigationController, UILabel;

@interface HeaderView : UIView
{
    BOOL _showsBackButton;
    UIView *_rightButton;
    UIView *_leftButton;
    NSString *_title;
    NavigationController *_navigationController;
    id <HeaderViewDelegate> _navigationDelegate;
    int _buttonStyle;
    UILabel *_titleLabel;
    NSArray *_horizontalConstraints;
    NSArray *_verticalConstraints;
    NSLayoutConstraint *_centeringConstraint;
}

+ (float)defaultHeight;
@property(retain, nonatomic) NSLayoutConstraint *centeringConstraint; // @synthesize centeringConstraint=_centeringConstraint;
@property(retain, nonatomic) NSArray *verticalConstraints; // @synthesize verticalConstraints=_verticalConstraints;
@property(retain, nonatomic) NSArray *horizontalConstraints; // @synthesize horizontalConstraints=_horizontalConstraints;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, nonatomic) int buttonStyle; // @synthesize buttonStyle=_buttonStyle;
@property(nonatomic) BOOL showsBackButton; // @synthesize showsBackButton=_showsBackButton;
@property(nonatomic) __weak id <HeaderViewDelegate> navigationDelegate; // @synthesize navigationDelegate=_navigationDelegate;
@property(nonatomic) __weak NavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIView *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) UIView *rightButton; // @synthesize rightButton=_rightButton;
- (void).cxx_destruct;
- (void)onBackButtonTapped:(id)arg1;
- (void)layoutToFit;
- (id)titleColorForStyle:(int)arg1;
- (void)onPress:(id)arg1;
- (void)setAutoresizingMask:(unsigned int)arg1;
- (id)initWithFrame:(struct CGRect)arg1 headerStyle:(int)arg2 buttonStyle:(int)arg3;
- (id)initWithHeaderStyle:(int)arg1 buttonStyle:(int)arg2;
- (id)init;

@end

