//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class UIActivityIndicatorView, UIImageView, UILabel, UIToolbar;

@interface HUD : UIWindow
{
    UIToolbar *_container;
    UILabel *_label;
    UIActivityIndicatorView *_progressIndicator;
    UIImageView *_successIndicator;
    UIImageView *_cancelIndicator;
}

+ (id)showWithText:(id)arg1 type:(int)arg2;
+ (id)flashWithText:(id)arg1 type:(int)arg2;
@property(retain, nonatomic) UIImageView *cancelIndicator; // @synthesize cancelIndicator=_cancelIndicator;
@property(retain, nonatomic) UIImageView *successIndicator; // @synthesize successIndicator=_successIndicator;
@property(retain, nonatomic) UIActivityIndicatorView *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIToolbar *container; // @synthesize container=_container;
- (void).cxx_destruct;
- (void)hide;
- (id)init;

@end

