//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGMediaRequestDelegate.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface IGBulkMediaRequestManager : NSObject <IGMediaRequestDelegate>
{
    NSMutableArray *_requests;
    NSObject<OS_dispatch_queue> *_requestQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *requestQueue; // @synthesize requestQueue=_requestQueue;
@property(retain, nonatomic) NSMutableArray *requests; // @synthesize requests=_requests;
- (void).cxx_destruct;
- (void)mediaRequest:(id)arg1 didFailWithError:(id)arg2 forURL:(id)arg3;
- (void)mediaRequest:(id)arg1 didLoadMediaWithData:(id)arg2 forURL:(id)arg3;
- (void)stopObservingRequests;
- (void)trimRequests;
- (void)addRequest:(id)arg1;
- (void)bulkFetchVideoURLs:(id)arg1 priority:(int)arg2 length:(long long)arg3;
- (void)bulkFetchImageURLs:(id)arg1 priority:(int)arg2;
- (void)dealloc;

@end

