//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFHTTPRequestOperationManager, AFNetworkReachabilityManager, NSOperationQueue;

@interface IGService : NSObject
{
    NSOperationQueue *_jsonParsingQueue;
    AFHTTPRequestOperationManager *_client;
    AFNetworkReachabilityManager *_reachabilityManager;
}

+ (id)userAgent;
+ (void)setBaseURL:(id)arg1;
+ (void)setAppName:(id)arg1;
+ (id)sharedService;
@property(readonly, nonatomic) AFNetworkReachabilityManager *reachabilityManager; // @synthesize reachabilityManager=_reachabilityManager;
@property(readonly, nonatomic) AFHTTPRequestOperationManager *client; // @synthesize client=_client;
- (void).cxx_destruct;
- (void)startJSONRequest:(id)arg1 responseHandler:(CDUnknownBlockType)arg2;
- (void)startRawRequest:(id)arg1 responseHandler:(CDUnknownBlockType)arg2;
- (id)init;

@end

