//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ImageFactory : NSObject
{
}

+ (id)borderedRoundedCopyOfImage:(id)arg1 size:(float)arg2 borderColor:(id)arg3 borderWidth:(float)arg4;
+ (id)roundedCopyOfImage:(id)arg1 size:(float)arg2;
+ (id)imageByApplyingTransform:(struct CGAffineTransform)arg1 toImage:(id)arg2;
+ (id)imageByFlippingImageHorizontally:(id)arg1;
+ (id)squareThumbnailImage:(id)arg1 size:(unsigned int)arg2;
+ (id)resizedImage:(id)arg1 cropRect:(struct CGRect)arg2 outputSize:(struct CGSize)arg3;
+ (struct CGRect)adjustedCropRect:(struct CGRect)arg1 forImage:(id)arg2;
+ (id)resizedImage:(id)arg1 size:(struct CGSize)arg2;
+ (id)resizedImage:(id)arg1 maxEdge:(unsigned int)arg2;
+ (id)dataFromData:(id)arg1 maxEdge:(unsigned int)arg2;
+ (id)dataFromImage:(id)arg1;
+ (id)blurredCopyOfImageForBackground:(id)arg1;
+ (id)blurredCopyOfImage:(id)arg1;
+ (id)imageWithContentsOfFile:(id)arg1 maxEdge:(unsigned int)arg2;
+ (id)imageWithData:(id)arg1 maxEdge:(unsigned int)arg2;
+ (struct CGSize)loadableImageSizeForImageSize:(struct CGSize)arg1;

@end

