//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JRModel.h"

@class NSDate, NSString, User;

@interface IncomingMessage : JRModel
{
    User *_cachedUser;
}

@property(retain) User *cachedUser; // @synthesize cachedUser=_cachedUser;
- (void).cxx_destruct;
- (void)prepareForDeletion;
@property(readonly) User *sender;
- (void)faultRelationships;
- (id)manager;

// Remaining properties
@property BOOL downloaded; // @dynamic downloaded;
@property BOOL hasReply; // @dynamic hasReply;
@property(readonly) BOOL isReply; // @dynamic isReply;
@property(readonly) NSString *mediaURL; // @dynamic mediaURL;
@property(readonly) NSString *previousText; // @dynamic previousText;
@property(readonly) float previousTextYOffset; // @dynamic previousTextYOffset;
@property(readonly) NSString *remoteID; // @dynamic remoteID;
@property(readonly) NSDate *sentDate; // @dynamic sentDate;
@property(readonly) NSString *text; // @dynamic text;
@property(readonly) float textYOffset; // @dynamic textYOffset;
@property(readonly) int type; // @dynamic type;
@property BOOL wantsDelete; // @dynamic wantsDelete;

@end

