//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface InstructionView : UIView
{
    UIImageView *_imageView;
    UILabel *_bulletLabel;
    UILabel *_textLabel;
}

@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UILabel *bulletLabel; // @synthesize bulletLabel=_bulletLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (id)initWithImage:(id)arg1 bulletNumber:(int)arg2 text:(id)arg3;

@end

