//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JRFileSystemUtilities : NSObject
{
}

+ (id)subUrlsAtUrls:(id)arg1 extensionFilters:(id)arg2;
+ (BOOL)addSkipBackupAttributeToItemAtURL:(id)arg1;
+ (id)applicationContentDirectoryUrl;
+ (id)applicationContentDirectory;

@end

