//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class JRModel, NSString;

@interface JRManagedObject : NSManagedObject
{
    JRModel *wrapper;
}

@property(nonatomic) __weak JRModel *wrapper; // @synthesize wrapper;
- (void).cxx_destruct;
- (void)prepareForDeletion;
- (void)awakeFromInsert;

// Remaining properties
@property(copy) NSString *uuid; // @dynamic uuid;

@end

