//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JRManagedObject, JRModelManager, NSMapTable, NSMutableDictionary, NSString;

@interface JRModel : NSObject
{
    JRManagedObject *_internal;
    NSString *_uuid;
    NSMutableDictionary *_cacheStorage;
    NSMapTable *_observers;
}

+ (BOOL)resolveInstanceMethod:(SEL)arg1;
@property(retain, nonatomic) NSMapTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) NSMutableDictionary *cacheStorage; // @synthesize cacheStorage=_cacheStorage;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (id)keyForSetter:(SEL)arg1;
- (id)keyForGetter:(SEL)arg1;
- (void)setCachedObject:(id)arg1 forKey:(id)arg2;
- (id)cachedObjectForKey:(id)arg1;
- (void)removeObserver:(id)arg1 forProperty:(id)arg2;
- (void)addObserver:(id)arg1 forProperty:(id)arg2 options:(unsigned int)arg3 handler:(CDUnknownBlockType)arg4;
- (void)prepareForDeletion;
- (void)performBlockAndWait:(CDUnknownBlockType)arg1;
- (void)performBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) JRModelManager *manager;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned int)arg3 context:(void *)arg4;
- (void)faultRelationships;
@property(retain) JRManagedObject *internal; // @synthesize internal=_internal;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (id)initWithManagedModel:(id)arg1;
- (void)dealloc;

@end

