//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureAudioDataOutputSampleBufferDelegate.h"
#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureAudioDataOutput, AVCaptureDevice, AVCaptureDeviceInput, AVCaptureSession, AVCaptureStillImageOutput, AVCaptureVideoDataOutput, AVCaptureVideoPreviewLayer, NSObject<OS_dispatch_queue>, NSPointerArray;

@interface LMCaptureManager : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate, AVCaptureAudioDataOutputSampleBufferDelegate>
{
    AVCaptureSession *_captureSession;
    NSObject<OS_dispatch_queue> *_captureQueue;
    AVCaptureDeviceInput *_videoInput;
    AVCaptureVideoDataOutput *_videoOutput;
    AVCaptureStillImageOutput *_stillImageOutput;
    AVCaptureVideoPreviewLayer *_previewLayer;
    AVCaptureDeviceInput *_audioInput;
    AVCaptureAudioDataOutput *_audioOutput;
    BOOL _isSessionStarted;
    BOOL _lockCount;
    BOOL _didLock;
    struct CGSize _bufferSize;
    NSPointerArray *_videoOutputs;
    NSPointerArray *_audioOutputs;
    BOOL _audioEnabled;
    int _devicePosition;
    CDUnknownBlockType _captureBlock;
}

+ (id)videoDeviceForPosition:(int)arg1;
+ (id)desiredFormatForDevice:(id)arg1;
+ (id)sharedManager;
@property(copy) CDUnknownBlockType captureBlock; // @synthesize captureBlock=_captureBlock;
@property(nonatomic, getter=isAudioEnabled) BOOL audioEnabled; // @synthesize audioEnabled=_audioEnabled;
@property(nonatomic) struct CGSize bufferSize; // @synthesize bufferSize=_bufferSize;
@property(nonatomic) int devicePosition; // @synthesize devicePosition=_devicePosition;
- (void).cxx_destruct;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)captureOutput:(id)arg1 didDropSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (BOOL)captureImageWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(nonatomic, getter=isSmoothAutoFocusEnabled) BOOL smoothAutoFocusEnabled;
- (void)resetMetering;
@property(nonatomic) int whiteBalanceMode;
@property(nonatomic) int focusMode;
- (void)setFocusMode:(int)arg1 atPoint:(struct CGPoint)arg2;
@property(nonatomic) int exposureMode;
- (void)setExposureMode:(int)arg1 atPoint:(struct CGPoint)arg2;
- (BOOL)isFlashModeSupported:(int)arg1;
@property(nonatomic) int flashMode;
- (void)unlockForConfiguration;
- (BOOL)lockForConfiguration;
- (void)startRunning;
@property(nonatomic) float zoom;
@property(readonly, nonatomic) AVCaptureVideoPreviewLayer *previewLayer;
- (void)configureSession;
- (void)configureAudioInput;
- (void)configureVideoInputWithDevicePosition:(int)arg1;
@property(readonly, nonatomic) AVCaptureDevice *videoDevice;
- (void)inspect:(CDUnknownBlockType)arg1;
- (void)addAudioOutput:(id)arg1;
- (void)addVideoOutput:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)init;
- (void)dealloc;

@end

