//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MCNearbyServiceAdvertiserDelegate.h"
#import "MCNearbyServiceBrowserDelegate.h"
#import "MCSessionDelegate.h"

@class MCNearbyServiceAdvertiser, MCNearbyServiceBrowser, MCPeerID, MCSession, NSMutableArray, NSMutableSet;

@interface LocalPeerController : NSObject <MCNearbyServiceAdvertiserDelegate, MCSessionDelegate, MCNearbyServiceBrowserDelegate>
{
    MCPeerID *_peerId;
    MCNearbyServiceAdvertiser *_advertiser;
    NSMutableSet *_blockedPeers;
    NSMutableArray *_peers;
    MCNearbyServiceBrowser *_peerBrowser;
    MCSession *_session;
    NSMutableSet *_peersDataHasBeenSentTo;
    NSMutableSet *_peersDataHasBeenReceivedFrom;
}

+ (void)invitePeer:(id)arg1;
+ (id)peers;
+ (void)start;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableSet *peersDataHasBeenReceivedFrom; // @synthesize peersDataHasBeenReceivedFrom=_peersDataHasBeenReceivedFrom;
@property(retain, nonatomic) NSMutableSet *peersDataHasBeenSentTo; // @synthesize peersDataHasBeenSentTo=_peersDataHasBeenSentTo;
@property(retain, nonatomic) MCSession *session; // @synthesize session=_session;
@property(retain, nonatomic) MCNearbyServiceBrowser *peerBrowser; // @synthesize peerBrowser=_peerBrowser;
@property(retain, nonatomic) NSMutableArray *peers; // @synthesize peers=_peers;
@property(retain, nonatomic) NSMutableSet *blockedPeers; // @synthesize blockedPeers=_blockedPeers;
@property(retain, nonatomic) MCNearbyServiceAdvertiser *advertiser; // @synthesize advertiser=_advertiser;
@property(retain, nonatomic) MCPeerID *peerId; // @synthesize peerId=_peerId;
- (void).cxx_destruct;
- (void)browser:(id)arg1 lostPeer:(id)arg2;
- (void)browser:(id)arg1 foundPeer:(id)arg2 withDiscoveryInfo:(id)arg3;
- (void)advertiser:(id)arg1 didReceiveInvitationFromPeer:(id)arg2 withContext:(id)arg3 invitationHandler:(CDUnknownBlockType)arg4;
- (void)session:(id)arg1 didFinishReceivingResourceWithName:(id)arg2 fromPeer:(id)arg3 atURL:(id)arg4 withError:(id)arg5;
- (void)session:(id)arg1 didStartReceivingResourceWithName:(id)arg2 fromPeer:(id)arg3 withProgress:(id)arg4;
- (void)session:(id)arg1 didReceiveStream:(id)arg2 withName:(id)arg3 fromPeer:(id)arg4;
- (void)session:(id)arg1 didReceiveData:(id)arg2 fromPeer:(id)arg3;
- (void)session:(id)arg1 peer:(id)arg2 didChangeState:(int)arg3;
- (id)init;
- (void)dealloc;

@end

