//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@interface MainWindow : UIWindow
{
    BOOL _validShakeStarted;
}

- (void)showRageShakeWithAction:(int)arg1;
- (void)motionEnded:(int)arg1 withEvent:(id)arg2;
- (void)motionBegan:(int)arg1 withEvent:(id)arg2;
- (void)shakeTimer:(id)arg1;

@end

