//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CaptureViewControllerDelegate.h"
#import "MessagesViewControllerDelegate.h"
#import "TrayManagementViewControllerDelegate.h"

@class CaptureViewController, ContactsDeniedViewController, MessagesViewController, NSDate, NSMapTable, NSMutableSet, Reachability, TrayManagementViewController, UIView;

@interface MainViewController : UIViewController <TrayManagementViewControllerDelegate, CaptureViewControllerDelegate, MessagesViewControllerDelegate>
{
    BOOL _fromRegistration;
    ContactsDeniedViewController *_contactsDeniedViewController;
    CaptureViewController *_captureViewController;
    MessagesViewController *_cardsViewController;
    TrayManagementViewController *_trayManagementViewController;
    int _pushFetchCount;
    int _messagesCount;
    NSMapTable *_sendScores;
    NSDate *_lastScoreCalculationTime;
    UIView *_sendPhotoNux;
    UIView *_sentPhotoNux;
    UIView *_nuxBackground;
    Reachability *_internetReachability;
    UIView *_noNetworkBanner;
    NSMutableSet *_capturingPhotosForUserIDs;
}

@property(retain, nonatomic) NSMutableSet *capturingPhotosForUserIDs; // @synthesize capturingPhotosForUserIDs=_capturingPhotosForUserIDs;
@property(retain, nonatomic) UIView *noNetworkBanner; // @synthesize noNetworkBanner=_noNetworkBanner;
@property(retain, nonatomic) Reachability *internetReachability; // @synthesize internetReachability=_internetReachability;
@property(retain, nonatomic) UIView *nuxBackground; // @synthesize nuxBackground=_nuxBackground;
@property(retain, nonatomic) UIView *sentPhotoNux; // @synthesize sentPhotoNux=_sentPhotoNux;
@property(retain, nonatomic) UIView *sendPhotoNux; // @synthesize sendPhotoNux=_sendPhotoNux;
@property(retain, nonatomic) NSDate *lastScoreCalculationTime; // @synthesize lastScoreCalculationTime=_lastScoreCalculationTime;
@property(retain, nonatomic) NSMapTable *sendScores; // @synthesize sendScores=_sendScores;
@property(nonatomic) int messagesCount; // @synthesize messagesCount=_messagesCount;
@property(nonatomic) int pushFetchCount; // @synthesize pushFetchCount=_pushFetchCount;
@property(retain, nonatomic) TrayManagementViewController *trayManagementViewController; // @synthesize trayManagementViewController=_trayManagementViewController;
@property(retain, nonatomic) MessagesViewController *cardsViewController; // @synthesize cardsViewController=_cardsViewController;
@property(retain, nonatomic) CaptureViewController *captureViewController; // @synthesize captureViewController=_captureViewController;
@property(retain, nonatomic) ContactsDeniedViewController *contactsDeniedViewController; // @synthesize contactsDeniedViewController=_contactsDeniedViewController;
@property(nonatomic) BOOL fromRegistration; // @synthesize fromRegistration=_fromRegistration;
- (void).cxx_destruct;
- (void)postMessageSentNotificationForUser:(id)arg1 image:(id)arg2;
- (void)trayManagementViewController:(id)arg1 wantsToSendVideoToUser:(id)arg2;
- (void)trayManagementViewControllerWantsToCancelRecordingVideo:(id)arg1;
- (void)trayManagementViewControllerStartRecordingVideo:(id)arg1 forUser:(id)arg2;
- (BOOL)trayManagementViewController:(id)arg1 canStartRecordingVideoForUser:(id)arg2;
- (void)trayManagementViewController:(id)arg1 wantsToSendPhotoToUser:(id)arg2;
- (void)trayManagementViewControllerWillEndManagement:(id)arg1;
- (void)trayManagementViewControllerWillBeginManagement:(id)arg1;
- (BOOL)trayManagementViewControllerShouldBeginManagement:(id)arg1;
- (void)messagesControllerWillManageFavorites:(id)arg1;
- (void)messagesControllerWillExpandMessages:(id)arg1;
- (void)messagesControllerDidCollapseMessages:(id)arg1;
- (void)messagesControllerDidHideMessagesIndicator:(id)arg1;
- (void)messagesControllerWillShowMessagesIndicator:(id)arg1;
- (BOOL)messagesControllerShouldExpandMessages:(id)arg1;
- (void)captureControllerDidEndDrawing:(id)arg1;
- (void)captureControllerDidBeginDrawing:(id)arg1;
- (void)captureViewControllerWantsCameraUnpause:(id)arg1;
- (void)captureControllerEndRecording:(id)arg1;
- (void)captureControllerDidStartRecording:(id)arg1;
- (void)captureControllerDidReachRecordingTimeLimit:(id)arg1;
- (void)captureControllerDidEndTextEditing:(id)arg1;
- (void)captureControllerDidBeginTextEditing:(id)arg1;
- (void)showRateLimitAlert;
- (BOOL)validateNewMediaSendToUser:(id)arg1;
- (void)updateScores;
- (void)onCloseButtonTapped:(id)arg1;
- (void)hideSentPhotoNux;
- (void)showSentPhotoNuxIsPhoto:(BOOL)arg1;
- (void)showSendPhotoNux;
- (void)onBannerTap:(id)arg1;
- (void)showNoInternetBanner;
- (void)removeNoInternetBanner;
- (void)onAddressBookAuthorizationChanged:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

@end

