//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JRManagedObject.h"

@class NSDate, NSSet, NSString;

@interface ManagedUser : JRManagedObject
{
}


// Remaining properties
@property(nonatomic) BOOL blocked; // @dynamic blocked;
@property(copy, nonatomic) NSString *countryCode; // @dynamic countryCode;
@property(nonatomic) BOOL favorite; // @dynamic favorite;
@property(copy, nonatomic) NSString *fullName; // @dynamic fullName;
@property(nonatomic) BOOL inAddressBook; // @dynamic inAddressBook;
@property(copy, nonatomic) NSSet *incomingMessages; // @dynamic incomingMessages;
@property(retain, nonatomic) NSDate *lastContactDate; // @dynamic lastContactDate;
@property(copy, nonatomic) NSString *nationalNumber; // @dynamic nationalNumber;
@property(nonatomic) int orderstamp; // @dynamic orderstamp;
@property(copy, nonatomic) NSString *profilePictureURL; // @dynamic profilePictureURL;
@property(copy, nonatomic) NSString *remoteID; // @dynamic remoteID;
@property(copy, nonatomic) NSString *shortName; // @dynamic shortName;
@end

