//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CardViewDelegate.h"

@class MediaCardView;

@protocol MediaCardViewDelegate <CardViewDelegate>
- (void)mediaCardViewDidExitCaptureMode:(MediaCardView *)arg1;
- (void)mediaCardViewDidEnterCaptureMode:(MediaCardView *)arg1;
- (void)mediaCardViewDidEndEditingText:(MediaCardView *)arg1;
- (void)mediaCardViewDidBeginEditingText:(MediaCardView *)arg1;
- (void)mediaCardViewDidReply:(MediaCardView *)arg1;
@end

