//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CardView.h"

#import "MessageAvatarViewDelegate.h"
#import "PhotoReplyViewDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITextViewDelegate.h"

@class IncomingMessage, MessageAvatarView, MessageTextContainer, PhotoReplyView, UIActivityIndicatorView, UIButton, UIImageView, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView;

@interface MediaCardView : CardView <UITextViewDelegate, UIGestureRecognizerDelegate, PhotoReplyViewDelegate, MessageAvatarViewDelegate, UIActionSheetDelegate>
{
    BOOL _didForceEndLastVideoRecording;
    BOOL _showsPreviousText;
    BOOL _isBlurred;
    IncomingMessage *_message;
    UIView *_imageViewContainer;
    UIImageView *_blurredImageView;
    UIActivityIndicatorView *_spinner;
    UIImageView *_addImageView;
    UIButton *_optionsButton;
    UIView *_nuxView;
    int _nuxType;
    UIButton *_cancelButton;
    UIButton *_sendReplyButton;
    UIButton *_photoReplyButton;
    PhotoReplyView *_photoReplyView;
    int _replyState;
    MessageTextContainer *_replyTextContainer;
    MessageTextContainer *_messageTextContainer;
    UITapGestureRecognizer *_tapRecognizer;
    UILongPressGestureRecognizer *_pressRecognizer;
    UIImageView *_gradientView;
    MessageAvatarView *_avatarView;
}

@property(retain, nonatomic) MessageAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UIImageView *gradientView; // @synthesize gradientView=_gradientView;
@property(retain, nonatomic) UILongPressGestureRecognizer *pressRecognizer; // @synthesize pressRecognizer=_pressRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer=_tapRecognizer;
@property(retain, nonatomic) MessageTextContainer *messageTextContainer; // @synthesize messageTextContainer=_messageTextContainer;
@property(retain, nonatomic) MessageTextContainer *replyTextContainer; // @synthesize replyTextContainer=_replyTextContainer;
@property(nonatomic) BOOL isBlurred; // @synthesize isBlurred=_isBlurred;
@property(nonatomic) int replyState; // @synthesize replyState=_replyState;
@property(retain, nonatomic) PhotoReplyView *photoReplyView; // @synthesize photoReplyView=_photoReplyView;
@property(retain, nonatomic) UIButton *photoReplyButton; // @synthesize photoReplyButton=_photoReplyButton;
@property(retain, nonatomic) UIButton *sendReplyButton; // @synthesize sendReplyButton=_sendReplyButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) int nuxType; // @synthesize nuxType=_nuxType;
@property(retain, nonatomic) UIView *nuxView; // @synthesize nuxView=_nuxView;
@property(retain, nonatomic) UIButton *optionsButton; // @synthesize optionsButton=_optionsButton;
@property(nonatomic) BOOL showsPreviousText; // @synthesize showsPreviousText=_showsPreviousText;
@property(retain, nonatomic) UIImageView *addImageView; // @synthesize addImageView=_addImageView;
@property(nonatomic) BOOL didForceEndLastVideoRecording; // @synthesize didForceEndLastVideoRecording=_didForceEndLastVideoRecording;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) UIImageView *blurredImageView; // @synthesize blurredImageView=_blurredImageView;
@property(retain, nonatomic) UIView *imageViewContainer; // @synthesize imageViewContainer=_imageViewContainer;
- (id)message;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)notifyDelegateOfReply;
- (void)updateAvatarAccessoryLabel;
- (void)writeMediaToCameraRoll;
- (BOOL)shouldShowSaveToCameraRoll;
- (void)photoReplyViewDidEndDrawing:(id)arg1;
- (void)photoReplyViewDidStartDrawing:(id)arg1;
- (void)photoReplyViewForceEndRecording:(id)arg1;
- (void)photoReplyViewWantsCancel:(id)arg1;
- (void)avatarViewDidFinishPress:(id)arg1;
- (void)avatarViewDidCancelPress:(id)arg1;
- (void)avatarViewDidStartPress:(id)arg1;
- (void)avatarViewDidRecieveTap:(id)arg1;
- (void)exitCaptureModeAnimated:(BOOL)arg1;
- (void)enterCaptureModeAnimated:(BOOL)arg1;
- (void)enterReplyMode;
- (void)textViewDidChange:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)transitionOutOfTextEditMode;
- (void)textViewDidEndEditing:(id)arg1;
- (void)transitionIntoTextEditMode;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)setBlurred:(BOOL)arg1 animated:(BOOL)arg2;
- (void)prepareBlurredViewForDisplay;
- (void)onPress:(id)arg1;
- (void)onTap:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)actionSheet:(id)arg1 willDismissWithButtonIndex:(int)arg2;
- (void)onOptionsButtonTapped:(id)arg1;
- (void)onOptionsButtonTouched:(id)arg1;
- (void)onSendReplyButtonTapped:(id)arg1;
- (void)onPhotoReplyButtonTouched:(id)arg1;
- (void)onPhotoReplyButtonTapped:(id)arg1;
- (void)onCancelTapped:(id)arg1;
- (void)handleBeingDismissed;
- (void)handleBecomingFrontmostCard;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)onKeyboardDidChangeFrame:(id)arg1;
- (void)onKeyboardWillShow:(id)arg1;
- (void)updateForKeyboardFrame:(struct CGRect)arg1;
- (void)showNuxWithText:(id)arg1;
- (void)addUserToFavorites:(id)arg1;
- (void)setMessage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(nonatomic) __weak id <MediaCardViewDelegate> delegate;

@end

