//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CardStackViewDataSource.h"
#import "CardStackViewDelegate.h"
#import "ContactCardViewDelegate.h"
#import "JRModelManagerSubscriber.h"
#import "MediaCardViewDelegate.h"
#import "SubviewsOnlyHitViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class ActivityIndicatorView, CardStackView, IncomingMessage, NSArray, NSCache, NSMutableArray, UIButton, UILabel, UISwipeGestureRecognizer, UIView;

@interface MessagesViewController : UIViewController <CardStackViewDataSource, CardStackViewDelegate, MediaCardViewDelegate, ContactCardViewDelegate, JRModelManagerSubscriber, SubviewsOnlyHitViewDelegate, UIGestureRecognizerDelegate>
{
    BOOL _cardsExpanded;
    BOOL _openCardsAfterLoad;
    BOOL _thumbnailVisible;
    id <MessagesViewControllerDelegate> _delegate;
    float _topContentInset;
    NSArray *_messages;
    int _lastMessageCount;
    NSMutableArray *_deletedMessages;
    UIView *_backgroundView;
    CardStackView *_stackView;
    ActivityIndicatorView *_loadingView;
    UILabel *_countLabel;
    UIButton *_thumbnailButton;
    UISwipeGestureRecognizer *_swipeRecognizer;
    int _fetchCount;
    IncomingMessage *_thumbnailMessage;
    NSCache *_thumbnailCache;
}

@property(retain, nonatomic) NSCache *thumbnailCache; // @synthesize thumbnailCache=_thumbnailCache;
@property(retain, nonatomic) IncomingMessage *thumbnailMessage; // @synthesize thumbnailMessage=_thumbnailMessage;
@property(nonatomic) int fetchCount; // @synthesize fetchCount=_fetchCount;
@property(nonatomic) BOOL thumbnailVisible; // @synthesize thumbnailVisible=_thumbnailVisible;
@property(retain, nonatomic) UISwipeGestureRecognizer *swipeRecognizer; // @synthesize swipeRecognizer=_swipeRecognizer;
@property(retain, nonatomic) UIButton *thumbnailButton; // @synthesize thumbnailButton=_thumbnailButton;
@property(nonatomic) BOOL openCardsAfterLoad; // @synthesize openCardsAfterLoad=_openCardsAfterLoad;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) ActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) CardStackView *stackView; // @synthesize stackView=_stackView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) NSMutableArray *deletedMessages; // @synthesize deletedMessages=_deletedMessages;
@property(nonatomic) int lastMessageCount; // @synthesize lastMessageCount=_lastMessageCount;
@property(retain, nonatomic) NSArray *messages; // @synthesize messages=_messages;
@property(nonatomic) BOOL cardsExpanded; // @synthesize cardsExpanded=_cardsExpanded;
@property(nonatomic) float topContentInset; // @synthesize topContentInset=_topContentInset;
@property(nonatomic) __weak id <MessagesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)removeMessageFromMessageList:(id)arg1;
- (id)messageAfterMessage:(id)arg1;
- (void)resultsUpdatedForRequest:(id)arg1 results:(id)arg2 changes:(id)arg3;
- (void)onMediaDownloadCountChanged:(id)arg1;
- (void)onUserOpenedAppFromPush:(id)arg1;
- (void)contactCardViewDidTryToFavorite:(id)arg1;
- (void)contactCardViewDidFavorite:(id)arg1;
- (void)saveContactFromCardView:(id)arg1 setFavorite:(BOOL)arg2;
- (void)mediaCardViewDidExitCaptureMode:(id)arg1;
- (void)mediaCardViewDidEnterCaptureMode:(id)arg1;
- (void)mediaCardViewDidReply:(id)arg1;
- (void)mediaCardViewDidEndEditingText:(id)arg1;
- (void)mediaCardViewDidBeginEditingText:(id)arg1;
- (void)cardViewWantsDismiss:(id)arg1;
- (void)stackController:(id)arg1 didDisplayView:(id)arg2;
- (void)stackController:(id)arg1 willDismissView:(id)arg2;
- (id)stackController:(id)arg1 viewAfterView:(id)arg2;
- (void)notifyDelegateFinishedLoading;
- (void)updateMessagesIndicator;
- (id)thumbnailForMessage:(id)arg1;
- (void)toggleCards:(id)arg1;
- (void)setHideThumbnailButton:(BOOL)arg1;
- (void)bounceButton;
- (void)setCardsExpanded:(BOOL)arg1 animated:(BOOL)arg2;
- (id)validMessages;
- (int)validMessagesCount;
- (void)onStackSwipe:(id)arg1;
- (void)onToggleCards:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)onDidFinishFetching:(id)arg1;
- (void)onDidStartFetching:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (BOOL)subviewsOnlyHitView:(id)arg1 shouldHitForSubview:(id)arg2 atPoint:(struct CGPoint)arg3;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

@end

