//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MessageAvatarView;

@protocol MessageAvatarViewDelegate <NSObject>
- (void)avatarViewDidFinishPress:(MessageAvatarView *)arg1;
- (void)avatarViewDidCancelPress:(MessageAvatarView *)arg1;
- (void)avatarViewDidStartPress:(MessageAvatarView *)arg1;
- (void)avatarViewDidRecieveTap:(MessageAvatarView *)arg1;

@optional
- (BOOL)avatarViewShouldRecieveTap:(MessageAvatarView *)arg1;
- (BOOL)avatarViewShouldRecievePress:(MessageAvatarView *)arg1;
@end

