//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "NetworkImageViewDelegate.h"

@class AvatarImageView, POPSpringAnimation, UIImageView, UILabel, UILongPressGestureRecognizer, UITapGestureRecognizer;

@interface MessageAvatarView : UIView <NetworkImageViewDelegate>
{
    BOOL _pressCanceled;
    BOOL _ignoreCurrentPress;
    BOOL _highlighted;
    BOOL _flipped;
    UIImageView *_shadowView;
    AvatarImageView *_imageView;
    UIView *_imageViewContainer;
    UILabel *_nameLabel;
    UILabel *_accessoryLabel;
    id <MessageAvatarViewDelegate> _delegate;
    UIView *_highlightView;
    UITapGestureRecognizer *_tapRecognzier;
    UILongPressGestureRecognizer *_pressRecognzier;
    POPSpringAnimation *_imageViewSpring;
    POPSpringAnimation *_textLabelSpring;
}

@property(retain, nonatomic) POPSpringAnimation *textLabelSpring; // @synthesize textLabelSpring=_textLabelSpring;
@property(retain, nonatomic) POPSpringAnimation *imageViewSpring; // @synthesize imageViewSpring=_imageViewSpring;
@property(nonatomic) BOOL flipped; // @synthesize flipped=_flipped;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) BOOL ignoreCurrentPress; // @synthesize ignoreCurrentPress=_ignoreCurrentPress;
@property(nonatomic) BOOL pressCanceled; // @synthesize pressCanceled=_pressCanceled;
@property(retain, nonatomic) UILongPressGestureRecognizer *pressRecognzier; // @synthesize pressRecognzier=_pressRecognzier;
@property(retain, nonatomic) UITapGestureRecognizer *tapRecognzier; // @synthesize tapRecognzier=_tapRecognzier;
@property(retain, nonatomic) UIView *highlightView; // @synthesize highlightView=_highlightView;
@property(nonatomic) __weak id <MessageAvatarViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *accessoryLabel; // @synthesize accessoryLabel=_accessoryLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIView *imageViewContainer; // @synthesize imageViewContainer=_imageViewContainer;
@property(retain, nonatomic) AvatarImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIImageView *shadowView; // @synthesize shadowView=_shadowView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGPoint)accessoryLabelCenter;
- (struct CGPoint)nameLabelCenter;
- (struct CGPoint)imageViewContainerCenter;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setFlipped:(BOOL)arg1 animated:(BOOL)arg2;
- (void)performHighlightGlow;
- (void)resetHighlightGlow;
- (void)performBounceWithVelocity:(float)arg1 andScale:(float)arg2;
- (void)performBounceWithVelocity:(float)arg1;
- (void)performBounceToScale:(float)arg1;
- (void)finishTouchBounce;
- (void)startTouchBounce;
- (id)scaleXYAnimation;
- (void)onPress:(id)arg1;
- (void)onTap:(id)arg1;
- (void)networkImageView:(id)arg1 didFailToLoadImageAtUrl:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

