//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MessagesViewController;

@protocol MessagesViewControllerDelegate <NSObject>
- (void)messagesControllerWillManageFavorites:(MessagesViewController *)arg1;
- (void)messagesControllerWillExpandMessages:(MessagesViewController *)arg1;
- (void)messagesControllerDidCollapseMessages:(MessagesViewController *)arg1;
- (void)messagesControllerDidHideMessagesIndicator:(MessagesViewController *)arg1;
- (void)messagesControllerWillShowMessagesIndicator:(MessagesViewController *)arg1;

@optional
- (BOOL)messagesControllerShouldExpandMessages:(MessagesViewController *)arg1;
@end

