//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIButton, UIFont, UITextView;

@interface MessageTextContainer : UIView
{
    BOOL _showsClearTextButton;
    UITextView *_textView;
    UIButton *_clearTextButton;
}

@property(nonatomic) BOOL showsClearTextButton; // @synthesize showsClearTextButton=_showsClearTextButton;
@property(retain, nonatomic) UIButton *clearTextButton; // @synthesize clearTextButton=_clearTextButton;
@property(readonly, nonatomic) UITextView *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
@property(nonatomic) BOOL selectable;
@property(nonatomic) BOOL editable;
@property(retain, nonatomic) UIFont *font;
@property(copy, nonatomic) NSString *text;
@property(readonly, nonatomic) BOOL hasText;
- (BOOL)becomeFirstResponder;
- (BOOL)isFirstResponder;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)onClearTextPressed:(id)arg1;
- (void)onTextChanged:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setCenter:(struct CGPoint)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutClearTextButton;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

