//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ModelParser : NSObject
{
}

+ (id)addMessageWithDictionary:(id)arg1;
+ (id)addUserFromTransientUser:(id)arg1 favorite:(int)arg2 blocked:(int)arg3;
+ (id)addUserWithDictionary:(id)arg1 favorite:(int)arg2 blocked:(int)arg3;
+ (id)addUsersWithArray:(id)arg1 favorite:(int)arg2 blocked:(int)arg3;
+ (id)transientUserWithDictionary:(id)arg1;

@end

