//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NameViewController;

@protocol NameViewControllerDelegate <NSObject>
- (void)nameViewController:(NameViewController *)arg1 didFinishWithPhoneNumber:(NSString *)arg2 countryCode:(NSString *)arg3 verificationCode:(NSString *)arg4 shortName:(NSString *)arg5 fullName:(NSString *)arg6 didPrefillName:(BOOL)arg7;
@end

