//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "RegistrationViewController.h"
#import "UITextFieldDelegate.h"

@class NSString, RegistrationNavigationController, UIButton, UITextField, UIView;

@interface NameViewController : BaseViewController <UITextFieldDelegate, RegistrationViewController>
{
    BOOL _didPrefillName;
    id <NameViewControllerDelegate> _delegate;
    NSString *_phoneNumber;
    NSString *_countryCode;
    NSString *_verificationCode;
    UIView *_containerView;
    UITextField *_secondTextField;
    UITextField *_firstTextField;
    UIButton *_nextButton;
}

@property(retain, nonatomic) UIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(nonatomic) BOOL didPrefillName; // @synthesize didPrefillName=_didPrefillName;
@property(retain, nonatomic) UITextField *firstTextField; // @synthesize firstTextField=_firstTextField;
@property(retain, nonatomic) UITextField *secondTextField; // @synthesize secondTextField=_secondTextField;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) NSString *verificationCode; // @synthesize verificationCode=_verificationCode;
@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(nonatomic) __weak id <NameViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)attemptToAutofillName;
- (void)finishIfReady;
- (void)updateNextButton;
- (BOOL)isReadyToFinish;
- (id)sanitizedFirstTextFieldText;
- (id)sanitizedSecondTextFieldText;
- (void)textFieldDidEndEditing:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)onNextButtonTapped:(id)arg1;
- (void)onLastNameTextFieldChanged:(id)arg1;
- (void)onFirstNameTextFieldChanged:(id)arg1;
- (void)onKeyboardDidChangeFrame:(id)arg1;
- (void)onKeyboardWillShow:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)updateForKeyboardFrame:(struct CGRect)arg1;
- (void)viewDidLoad;
@property(readonly, nonatomic) int preferredGradientType;
- (BOOL)requiresOverlayView;
@property(readonly, nonatomic) BOOL isCurrentLocaleFullNameLocale;
- (id)initWithPhoneNumber:(id)arg1 countryCode:(id)arg2 verificationCode:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, nonatomic) RegistrationNavigationController *pp_navigationController;

@end

