//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, UIScreenEdgePanGestureRecognizer;

@interface NavigationController : UIViewController <UIGestureRecognizerDelegate>
{
    BOOL _disableGestureBasedPop;
    BOOL _performingEdgeGesture;
    int _buttonStyle;
    UIScreenEdgePanGestureRecognizer *_edgeRecognizer;
    NSMutableArray *_controllers;
}

@property(retain, nonatomic) NSMutableArray *controllers; // @synthesize controllers=_controllers;
@property(nonatomic) BOOL performingEdgeGesture; // @synthesize performingEdgeGesture=_performingEdgeGesture;
@property(retain, nonatomic) UIScreenEdgePanGestureRecognizer *edgeRecognizer; // @synthesize edgeRecognizer=_edgeRecognizer;
@property(nonatomic) BOOL disableGestureBasedPop; // @synthesize disableGestureBasedPop=_disableGestureBasedPop;
@property(nonatomic) int buttonStyle; // @synthesize buttonStyle=_buttonStyle;
- (void).cxx_destruct;
- (void)onScreenEdgeGesture:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
@property(readonly, nonatomic) UIViewController *topMostViewController;
- (void)popViewControllerAnimated:(BOOL)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithRootViewController:(id)arg1;

@end

