//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSString, Reachability, UIImage;

@interface NetworkImageView : UIImageView
{
    id <NetworkImageViewDelegate> _delegate;
    NSString *_url;
    id _downloadToken;
    int _retryCount;
    Reachability *_reachability;
    int _tick;
    UIImage *_imageCopy;
}

@property(nonatomic) UIImage *imageCopy; // @synthesize imageCopy=_imageCopy;
@property(nonatomic) int tick; // @synthesize tick=_tick;
@property(retain, nonatomic) Reachability *reachability; // @synthesize reachability=_reachability;
@property int retryCount; // @synthesize retryCount=_retryCount;
@property(retain, nonatomic) id downloadToken; // @synthesize downloadToken=_downloadToken;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) __weak id <NetworkImageViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cancelImageLoad;
- (void)doLoadImageAtUrl:(id)arg1;
- (void)loadImageAtUrl:(id)arg1 clearPreviousImage:(BOOL)arg2;
- (void)loadImageAtUrl:(id)arg1;
- (void)loadLocalImage:(id)arg1 withUrl:(id)arg2;
- (int)maxImageEdge;
- (void)loadIfNecessary;
- (id)prepareImage:(id)arg1 forUrl:(id)arg2;
- (void)reprepareImage;
- (id)placeholderImage;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

