//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NetworkImageView, UIImage;

@protocol NetworkImageViewDelegate <NSObject>

@optional
- (void)networkImageView:(NetworkImageView *)arg1 didUpdateImageDownloadProgress:(float)arg2;
- (void)networkImageView:(NetworkImageView *)arg1 didFailToLoadImageAtUrl:(NSString *)arg2;
- (void)networkImageView:(NetworkImageView *)arg1 didLoadImageAtUrl:(NSString *)arg2;
- (void)networkImageView:(NetworkImageView *)arg1 willSetImage:(UIImage *)arg2 forUrl:(NSString *)arg3;
- (void)networkImageView:(NetworkImageView *)arg1 willPrepareImage:(UIImage *)arg2 forUrl:(NSString *)arg3;
@end

