//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface NetworkCoordinator : NSObject
{
    NSMutableDictionary *_requestorMap;
    NSMutableArray *_requestors;
    NSMutableDictionary *_connectionMap;
    NSMutableDictionary *_uploadConnectionMap;
    NSMutableArray *_uploadRequestors;
}

+ (BOOL)cancelRequestForToken:(id)arg1;
+ (id)enqueueRequest:(id)arg1;
+ (BOOL)validateRequest:(id)arg1;
+ (id)baseAPIURL;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *uploadRequestors; // @synthesize uploadRequestors=_uploadRequestors;
@property(retain, nonatomic) NSMutableDictionary *uploadConnectionMap; // @synthesize uploadConnectionMap=_uploadConnectionMap;
@property(retain, nonatomic) NSMutableDictionary *connectionMap; // @synthesize connectionMap=_connectionMap;
@property(retain, nonatomic) NSMutableArray *requestors; // @synthesize requestors=_requestors;
@property(retain, nonatomic) NSMutableDictionary *requestorMap; // @synthesize requestorMap=_requestorMap;
- (void).cxx_destruct;
- (BOOL)cancelRequestForToken:(id)arg1;
- (id)enqueueUploadForUrl:(id)arg1 method:(id)arg2 uuid:(id)arg3 cachePolicy:(unsigned int)arg4 shouldSign:(BOOL)arg5 parameters:(id)arg6 files:(id)arg7 completionHandler:(CDUnknownBlockType)arg8 progressHandler:(CDUnknownBlockType)arg9;
- (id)enqueueRequestForUrl:(id)arg1 useOutputFile:(BOOL)arg2 method:(id)arg3 cachePolicy:(unsigned int)arg4 shouldSign:(BOOL)arg5 parameters:(id)arg6 files:(id)arg7 priority:(int)arg8 completionHandler:(CDUnknownBlockType)arg9 willStartRequestBlock:(CDUnknownBlockType)arg10 progressHandler:(CDUnknownBlockType)arg11;
- (void)processConnections;
- (void)performUploadWithRequestor:(id)arg1;
- (void)performRequestForRequestor:(id)arg1;
- (id)mapKeyForRequestor:(id)arg1;
- (void)logInfo;
- (id)init;

@end

