//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (PPAdditions)
+ (id)pp_invalidCharacterSet;
- (id)pp_removeNonLetterCharacters;
- (BOOL)pp_hasInvalidCharacters;
- (id)pp_URLDecodedString;
- (id)pp_URLEncodedString;
@end

