//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (PPPhoneNumber)
+ (id)pp_countryCodeForISOCode:(id)arg1;
+ (id)pp_phoneNumberStringWithCountryCode:(id)arg1 nationalNumber:(id)arg2;
- (id)pp_formattedPhoneNumberWithISOCode:(id)arg1;
- (BOOL)pp_isValidPhoneNumberWithISOCode:(id)arg1;
- (id)pp_phoneNumberDigits;
@end

