//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JRModel.h"

@class NSDate, NSString;

@interface OutgoingMessage : JRModel
{
}

- (void)prepareForDeletion;
- (id)manager;

// Remaining properties
@property(readonly) NSString *previousMessageRemoteID; // @dynamic previousMessageRemoteID;
@property(readonly) NSString *recipientRemoteID; // @dynamic recipientRemoteID;
@property(readonly) int sendType; // @dynamic sendType;
@property(readonly) NSDate *sentDate; // @dynamic sentDate;
@property(readonly) NSString *text; // @dynamic text;
@property(readonly) float textYOffset; // @dynamic textYOffset;
@property(readonly) int type; // @dynamic type;

@end

