//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "CountryPickerViewControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class Country, NSDictionary, NSString, UIButton, UIColor, UITextField, UIView, UIViewController;

@interface PhoneNumberField : UIControl <UITextFieldDelegate, CountryPickerViewControllerDelegate>
{
    UIColor *_previousColor;
    UIViewController *_presentationController;
    NSDictionary *_countryCodeTextAttributes;
    UIColor *_countryCodeHighlightColor;
    Country *_country;
    UIView *_countryCodeOutline;
    UIButton *_countryCodeButton;
    UITextField *_phoneNumberField;
}

@property(retain, nonatomic) UITextField *phoneNumberField; // @synthesize phoneNumberField=_phoneNumberField;
@property(retain, nonatomic) UIButton *countryCodeButton; // @synthesize countryCodeButton=_countryCodeButton;
@property(retain, nonatomic) UIView *countryCodeOutline; // @synthesize countryCodeOutline=_countryCodeOutline;
@property(retain, nonatomic) Country *country; // @synthesize country=_country;
@property(retain, nonatomic) UIColor *countryCodeHighlightColor; // @synthesize countryCodeHighlightColor=_countryCodeHighlightColor;
@property(retain, nonatomic) NSDictionary *countryCodeTextAttributes; // @synthesize countryCodeTextAttributes=_countryCodeTextAttributes;
@property(nonatomic) __weak UIViewController *presentationController; // @synthesize presentationController=_presentationController;
- (void).cxx_destruct;
- (void)onCountryCodeUp:(id)arg1;
- (void)onCountryCodeDown:(id)arg1;
- (void)countryPickerDidCancel:(id)arg1;
- (void)countryPicker:(id)arg1 didPickCountry:(id)arg2;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)onEditingChanged:(id)arg1;
- (void)onCountryCodePresssed:(id)arg1;
- (void)updateCountryCodeField;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)setCountryCode:(id)arg1;
@property(readonly, nonatomic) NSString *countryCode;
@property(readonly, nonatomic) NSString *phoneNumber;
@property(retain, nonatomic) NSDictionary *phoneNumberTextAttributes;
@property(retain, nonatomic) UIColor *tintColor;
@property(retain, nonatomic) UIColor *countryCodeBorderColor;
@property(retain, nonatomic) UIColor *countryCodeFillColor;
- (void)layoutSubviews;

@end

