//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "RegistrationViewController.h"
#import "WebViewControllerDelegate.h"

@class PhoneNumberField, RegistrationNavigationController, UIButton, UIView;

@interface PhoneNumberViewController : BaseViewController <WebViewControllerDelegate, RegistrationViewController>
{
    BOOL _hasEnteredText;
    id <PhoneNumberViewControllerDelegate> _delegate;
    UIButton *_nextButton;
    UIView *_containerView;
    PhoneNumberField *_phoneNumberField;
}

@property(nonatomic) BOOL hasEnteredText; // @synthesize hasEnteredText=_hasEnteredText;
@property(retain, nonatomic) PhoneNumberField *phoneNumberField; // @synthesize phoneNumberField=_phoneNumberField;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(nonatomic) __weak id <PhoneNumberViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)getVerificationCode;
- (void)webViewControllerWantsDismissal:(id)arg1;
- (void)onTermsButtonTapped;
- (void)onNextButtonTapped:(id)arg1;
- (void)updateNextButton;
- (void)markHasEnteredText;
- (void)onKeyboardDidChangeFrame:(id)arg1;
- (void)onKeyboardWillShow:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)updateForKeyboardFrame:(struct CGRect)arg1;
- (void)viewDidLoad;
@property(readonly, nonatomic) int preferredGradientType;
- (BOOL)requiresOverlayView;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, nonatomic) RegistrationNavigationController *pp_navigationController;

@end

