//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MediaCardView.h"

@class UIImageView;

@interface PhotoCardView : MediaCardView
{
    UIImageView *_imageView;
    PhotoCardView *_strongSelf;
}

@property(retain, nonatomic) PhotoCardView *strongSelf; // @synthesize strongSelf=_strongSelf;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)writeMediaToCameraRoll;
- (void)setMessage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

