//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PhotoReplyView;

@protocol PhotoReplyViewDelegate <NSObject>
- (void)photoReplyViewDidEndDrawing:(PhotoReplyView *)arg1;
- (void)photoReplyViewDidStartDrawing:(PhotoReplyView *)arg1;
- (void)photoReplyViewForceEndRecording:(PhotoReplyView *)arg1;
- (void)photoReplyViewWantsCancel:(PhotoReplyView *)arg1;
@end

