//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CaptureViewControllerDelegate.h"

@class CaptureViewController, IncomingMessage, UIButton;

@interface PhotoReplyView : UIView <CaptureViewControllerDelegate>
{
    CaptureViewController *_captureViewController;
    id <PhotoReplyViewDelegate> _delegate;
    IncomingMessage *_message;
    UIButton *_cancelButton;
}

@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) IncomingMessage *message; // @synthesize message=_message;
@property(nonatomic) __weak id <PhotoReplyViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CaptureViewController *captureViewController; // @synthesize captureViewController=_captureViewController;
- (void).cxx_destruct;
- (void)captureControllerDidEndDrawing:(id)arg1;
- (void)captureControllerDidBeginDrawing:(id)arg1;
- (void)captureControllerEndRecording:(id)arg1;
- (void)captureControllerDidStartRecording:(id)arg1;
- (void)captureControllerDidReachRecordingTimeLimit:(id)arg1;
- (void)captureControllerDidEndTextEditing:(id)arg1;
- (void)captureControllerDidBeginTextEditing:(id)arg1;
- (void)onCancelTouched:(id)arg1;
- (void)onCancelTapped:(id)arg1;
- (void)cancelRecording;
- (void)replyWithVideoWithCompletion:(CDUnknownBlockType)arg1;
- (void)startRecording;
- (void)replyWithPhotoWithCompletion:(CDUnknownBlockType)arg1;
- (id)captureVC;
- (id)initWithFrame:(struct CGRect)arg1 message:(id)arg2;

@end

