//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UILabel, UIPickerView;

@interface PickerField : UIControl
{
    UIPickerView *_inputView;
    UILabel *_titleLabel;
    struct CGSize _labelPadding;
}

@property(nonatomic) struct CGSize labelPadding; // @synthesize labelPadding=_labelPadding;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIPickerView *inputView; // @synthesize inputView=_inputView;
- (void).cxx_destruct;
- (BOOL)canBecomeFirstResponder;
- (void)onTap:(id)arg1;
- (void)updateLabelLayout;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

