//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TableViewController.h"

#import "JRModelManagerSubscriber.h"
#import "UIActionSheetDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UserSearchViewControllerDelegate.h"

@class NSArray, UIActivityIndicatorView, UIView, UserSearchViewController;

@interface PrivacySettingsViewController : TableViewController <UITableViewDataSource, UITableViewDelegate, JRModelManagerSubscriber, UserSearchViewControllerDelegate, UIActionSheetDelegate>
{
    NSArray *_blockedUsers;
    UIActivityIndicatorView *_spinner;
    UIView *_searchControllerOverlay;
    UserSearchViewController *_searchController;
}

@property(retain, nonatomic) UserSearchViewController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) UIView *searchControllerOverlay; // @synthesize searchControllerOverlay=_searchControllerOverlay;
@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) NSArray *blockedUsers; // @synthesize blockedUsers=_blockedUsers;
- (void).cxx_destruct;
- (void)makeUserSearchable:(BOOL)arg1;
- (void)resultsUpdatedForRequest:(id)arg1 results:(id)arg2 changes:(id)arg3;
- (void)userSearchViewControllerDidTapCancel:(id)arg1;
- (void)userSearchViewController:(id)arg1 didSelectUser:(id)arg2;
- (void)userSearchViewController:(id)arg1 willShowUser:(id)arg2;
- (void)dismissUserSearchViewController:(id)arg1;
- (void)enterSearchMode;
- (void)didSelectBlockedUserAtIndexPath:(id)arg1;
- (void)didSelectBlockActionAtIndex:(int)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 blockedUserCellForIndexPath:(id)arg2;
- (id)tableView:(id)arg1 blockActionCellForIndexPath:(id)arg2;
- (id)tableView:(id)arg1 searchableCellForIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)onBackgroundTapped:(id)arg1;
- (id)detailTextForIndexPath:(id)arg1;
- (BOOL)willShowAccessoryForIndexPath:(id)arg1;
- (BOOL)shouldShowBlockedUsers;
- (void)setUpTableView;
- (void)setUpHeaderView;
- (void)onKeyboardWillHide:(id)arg1;
- (void)onKeyboardWillShow:(id)arg1;
- (void)updateForKeyboardFrame:(struct CGRect)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

