//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Profile : NSObject
{
}

+ (void)deleteAccountWithCompletion:(CDUnknownBlockType)arg1;
+ (void)updateProfileWithPropertyChanges:(id)arg1 files:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)setSearchable:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)updateWithShortName:(id)arg1 fullName:(id)arg2 avatar:(id)arg3 completion:(CDUnknownBlockType)arg4;

@end

