//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TableViewController.h"

#import "JRModelManagerSubscriber.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray;

@interface RecentUsersListViewController : TableViewController <UITableViewDataSource, UITableViewDelegate, JRModelManagerSubscriber>
{
    NSArray *_recentUsers;
}

@property(retain, nonatomic) NSArray *recentUsers; // @synthesize recentUsers=_recentUsers;
- (void).cxx_destruct;
- (void)resultsUpdatedForRequest:(id)arg1 results:(id)arg2 changes:(id)arg3;
- (void)confirmUnblockUser:(id)arg1 atIndexPath:(id)arg2;
- (void)confirmBlockUser:(id)arg1 atIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)setUpTableView;
- (void)setUpHeaderView;
- (id)init;

@end

