//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MessageAvatarViewDelegate.h"

@class CALayer, MessageAvatarView, User;

@interface RecipientCell : UIView <MessageAvatarViewDelegate>
{
    BOOL _editing;
    BOOL _recordingCancelled;
    User *_user;
    MessageAvatarView *_avatarView;
    id <RecipientCellDelegate> _delegate;
}

@property(nonatomic) BOOL recordingCancelled; // @synthesize recordingCancelled=_recordingCancelled;
@property(nonatomic) __weak id <RecipientCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL editing; // @synthesize editing=_editing;
@property(retain, nonatomic) MessageAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) User *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (BOOL)avatarViewShouldRecievePress:(id)arg1;
- (BOOL)avatarViewShouldRecieveTap:(id)arg1;
- (void)avatarViewDidFinishPress:(id)arg1;
- (void)avatarViewDidCancelPress:(id)arg1;
- (void)avatarViewDidStartPress:(id)arg1;
- (void)avatarViewDidRecieveTap:(id)arg1;
- (void)restartAnimation;
- (void)resetHighlightGlow;
- (void)performSpringToTop:(BOOL)arg1 animated:(BOOL)arg2;
- (void)performSpin;
- (void)didMoveToSuperview;
@property(readonly, nonatomic) struct CGRect contentHitRect;
- (void)resetAnimations;
- (id)translateYAnimation;
@property(readonly, nonatomic) CALayer *animationLayer;
- (void)reset;
- (id)initWithFrame:(struct CGRect)arg1;

@end

