//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RecipientCell;

@protocol RecipientCellDelegate <NSObject>
- (void)recipientCellDidFinishPress:(RecipientCell *)arg1 wasCancelled:(BOOL)arg2;
- (void)recipientCellDidStartPress:(RecipientCell *)arg1;
- (BOOL)recipientCellShouldStartPress:(RecipientCell *)arg1;
- (void)recipientCellWasTapped:(RecipientCell *)arg1;
@end

