//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAShapeLayer;

@interface RecordingIndicator : UIView
{
    float _progress;
    CAShapeLayer *_fillLayer;
    CAShapeLayer *_borderLayer;
    CAShapeLayer *_borderUnderlayLayer;
}

@property(retain, nonatomic) CAShapeLayer *borderUnderlayLayer; // @synthesize borderUnderlayLayer=_borderUnderlayLayer;
@property(retain, nonatomic) CAShapeLayer *borderLayer; // @synthesize borderLayer=_borderLayer;
@property(retain, nonatomic) CAShapeLayer *fillLayer; // @synthesize fillLayer=_fillLayer;
@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)updateShapeLayerAnimated:(BOOL)arg1;
- (void)setProgress:(float)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

