//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RegistrationNavigationController;

@protocol RegistrationViewController <NSObject>
@property(readonly, nonatomic) RegistrationNavigationController *pp_navigationController;
@property(readonly, nonatomic) int preferredGradientType;
- (BOOL)requiresOverlayView;
@end

