//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ContactsViewController.h"

@class ActivityIndicatorView, NSMutableOrderedSet, UILabel;

@interface RegistrationContactsViewController : ContactsViewController
{
    BOOL _downloadingFavorites;
    ActivityIndicatorView *_loadingView;
    UILabel *_loadingLabel;
    NSMutableOrderedSet *_usersToPreCacheAvatarsFor;
}

@property(retain, nonatomic) NSMutableOrderedSet *usersToPreCacheAvatarsFor; // @synthesize usersToPreCacheAvatarsFor=_usersToPreCacheAvatarsFor;
@property(nonatomic) BOOL downloadingFavorites; // @synthesize downloadingFavorites=_downloadingFavorites;
@property(retain, nonatomic) UILabel *loadingLabel; // @synthesize loadingLabel=_loadingLabel;
@property(retain, nonatomic) ActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
- (void).cxx_destruct;
- (void)sendDoneDelegateCallback;
- (BOOL)showDescriptionText;
- (BOOL)shouldShowContactsToInvite;
- (void)handleDidEnterSearch;
- (void)handleHasContactsAccess;
- (id)doneButtonTitle;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)downloadFavorites;
- (void)handleUserListDidUpdateToList:(id)arg1;
- (void)handleRecentListDidUpdateToList:(id)arg1;
- (void)preCacheAvatarsForUsers:(id)arg1;

@end

