//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NavigationController.h"

#import "AccountCheckViewControllerDelegate.h"
#import "AvatarViewControllerDelegate.h"
#import "NameViewControllerDelegate.h"
#import "PhoneNumberVerificationViewControllerDelegate.h"
#import "PhoneNumberViewControllerDelegate.h"

@class CrystalBackgroundView, UIImage;

@interface RegistrationNavigationController : NavigationController <PhoneNumberViewControllerDelegate, PhoneNumberVerificationViewControllerDelegate, NameViewControllerDelegate, AvatarViewControllerDelegate, AccountCheckViewControllerDelegate>
{
    id <RegistrationNavigationControllerDelegate> _registrationDelegate;
    CrystalBackgroundView *_backgroundView;
    UIImage *_currentPendingAvatar;
    struct CGRect _overlayFrame;
}

@property(nonatomic) struct CGRect overlayFrame; // @synthesize overlayFrame=_overlayFrame;
@property(retain, nonatomic) UIImage *currentPendingAvatar; // @synthesize currentPendingAvatar=_currentPendingAvatar;
@property(retain, nonatomic) CrystalBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) __weak id <RegistrationNavigationControllerDelegate> registrationDelegate; // @synthesize registrationDelegate=_registrationDelegate;
- (void).cxx_destruct;
- (void)avatarViewController:(id)arg1 didPickAvatarImage:(id)arg2;
- (void)avatarViewController:(id)arg1 didFinishWithPhoneNumber:(id)arg2 countryCode:(id)arg3 verificationCode:(id)arg4 shortName:(id)arg5 fullName:(id)arg6 avatar:(id)arg7;
- (void)nameViewController:(id)arg1 didFinishWithPhoneNumber:(id)arg2 countryCode:(id)arg3 verificationCode:(id)arg4 shortName:(id)arg5 fullName:(id)arg6 didPrefillName:(BOOL)arg7;
- (void)accountCheckViewController:(id)arg1 wantsNewAccountWithPhoneNumber:(id)arg2 countryCode:(id)arg3 verificationCode:(id)arg4;
- (void)accountCheckViewControllerDidLogIn:(id)arg1;
- (void)phoneNumberVerificationViewController:(id)arg1 didFinishWithPhoneNumber:(id)arg2 countryCode:(id)arg3 verificationCode:(id)arg4 existingUser:(id)arg5;
- (void)phoneNumberVerificationViewControllerDidLogIn:(id)arg1;
- (void)phoneNumberViewController:(id)arg1 didFinishWithPhoneNumber:(id)arg2 countryCode:(id)arg3;
- (void)phoneNumberViewControllerDidLogIn:(id)arg1;
- (void)updateOverlayFrame:(struct CGRect)arg1 forViewController:(id)arg2;
- (void)updateOverlayViewVisibilityForViewController:(id)arg1 animated:(BOOL)arg2;
- (void)popViewControllerAnimated:(BOOL)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (BOOL)shouldUseFastTransitionToController:(id)arg1;
- (BOOL)showOverlayViewForController:(id)arg1;
- (void)viewDidLoad;
- (void)markNuxesCompletedBecauseOfExistingUser;
- (id)init;

@end

