//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RegistrationUIFactory : NSObject
{
}

+ (id)secondaryOptionButton;
+ (id)primaryOptionButton;
+ (id)loadingSpinnerView;
+ (id)nextButton;
+ (id)descriptionLabel;
+ (id)finePrintLabel;
+ (id)pickerField;
+ (id)textField;
+ (id)subtitleLabel;
+ (id)titleLabelDark;
+ (id)titleLabel;
+ (id)finePrintString:(id)arg1 withLinkString:(id)arg2 controlState:(unsigned int)arg3;
+ (id)descriptionString:(id)arg1 alpha:(float)arg2;
+ (id)titleString:(id)arg1 isLarge:(BOOL)arg2 subtitleString:(id)arg3;
+ (id)largeTitleString:(id)arg1 subtitleString:(id)arg2;
+ (id)titleString:(id)arg1 subtitleString:(id)arg2;
+ (id)titleString:(id)arg1;

@end

