//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString, NSURLRequest;

@interface Requestor : NSObject
{
    BOOL _shouldSign;
    BOOL _useOutputFile;
    int _priority;
    unsigned int _cachePolicy;
    NSString *_url;
    NSString *_method;
    NSString *_uuid;
    NSDictionary *_parameters;
    NSArray *_files;
    CDUnknownBlockType _completionHandler;
    CDUnknownBlockType _willStartRequestBlock;
    CDUnknownBlockType _progressHandler;
}

+ (id)requestorWithUrl:(id)arg1 useOutputFile:(BOOL)arg2 method:(id)arg3 uuid:(id)arg4 cachePolicy:(unsigned int)arg5 shouldSign:(BOOL)arg6 parameters:(id)arg7 priority:(int)arg8 files:(id)arg9 completionHandler:(CDUnknownBlockType)arg10 willStartRequestBlock:(CDUnknownBlockType)arg11 progressBlock:(CDUnknownBlockType)arg12;
@property(readonly, nonatomic) CDUnknownBlockType progressHandler; // @synthesize progressHandler=_progressHandler;
@property(readonly, nonatomic) CDUnknownBlockType willStartRequestBlock; // @synthesize willStartRequestBlock=_willStartRequestBlock;
@property(readonly, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(readonly, nonatomic) NSArray *files; // @synthesize files=_files;
@property(readonly, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(readonly, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(readonly, nonatomic) NSString *method; // @synthesize method=_method;
@property(readonly, nonatomic) NSString *url; // @synthesize url=_url;
@property(readonly, nonatomic) unsigned int cachePolicy; // @synthesize cachePolicy=_cachePolicy;
@property(readonly, nonatomic) BOOL useOutputFile; // @synthesize useOutputFile=_useOutputFile;
@property(readonly, nonatomic) BOOL shouldSign; // @synthesize shouldSign=_shouldSign;
@property(nonatomic) int priority; // @synthesize priority=_priority;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *uniqueRequestKey;
@property(readonly, nonatomic) NSURLRequest *preparedUrlRequest;
- (BOOL)shouldSetHTTPBody;
- (id)description;

@end

