//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary, NSError, NSString;

@interface Response : NSObject
{
    int _statusCode;
    NSError *_error;
    NSData *_data;
    NSString *_path;
    NSDictionary *_json;
}

+ (id)responseWithStatusCode:(int)arg1 path:(id)arg2 error:(id)arg3;
+ (id)responseWithStatusCode:(int)arg1 data:(id)arg2 error:(id)arg3;
@property(retain, nonatomic) NSDictionary *json; // @synthesize json=_json;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) int statusCode; // @synthesize statusCode=_statusCode;
- (void).cxx_destruct;
- (id)description;
@property(readonly, nonatomic) BOOL success;

@end

