//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TableViewController.h"

#import "AvatarTableViewCellDelegate.h"
#import "EditNameViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WebViewControllerDelegate.h"

@interface SettingsViewController : TableViewController <UITableViewDataSource, UITableViewDelegate, EditNameViewControllerDelegate, AvatarTableViewCellDelegate, WebViewControllerDelegate>
{
    id <SettingsViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SettingsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)editProfileViewControllerDidFinish:(id)arg1;
- (void)avatarCell:(id)arg1 didChooseImage:(id)arg2;
- (id)avatarCellViewControllerForPresentation:(id)arg1;
- (void)onDoneButtonTapped:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 simpleCellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 avatarCellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)webViewControllerWantsDismissal:(id)arg1;
- (void)setUpTableView;
- (void)setUpHeaderView;
- (void)viewDidLoad;
- (id)init;

@end

