//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SoundManager : NSObject
{
}

+ (void)playReplyPictureText;
+ (void)playReplyOpen;
+ (void)playReplySuccessClickSound;
+ (void)playReplySelectSound;
+ (void)playReplyLaunchSound;
+ (void)playAvatarCancelSound;
+ (void)playAvatarSaveEnd;
+ (void)playAvatarSaveStart;
+ (void)playAvatarRetake;
+ (void)playAvatarCameraFlash;
+ (void)playSettingsRowTouched;
+ (void)playUserSettingsOpened;
+ (void)resetIncreasedCount:(id)arg1;
+ (void)playCountIncreasedAgain;
+ (void)playCountIncreased;
+ (void)playShowThumbnail;
+ (void)playCardsCloseEnd;
+ (void)playCardsCloseStart;
+ (void)playCardsOpenEnd;
+ (void)playCardsOpenStart;
+ (void)playKeyboardClosed;
+ (void)playTextButtonSoundB;
+ (void)playTextButtonSoundA;
+ (void)playFlashDeactivated;
+ (void)playFlashActivated;
+ (void)playFlashTouch;
+ (void)playPushUpEnd;
+ (void)playPushUpBegin;
+ (void)playSlideCancelSound;
+ (void)playReadSound;
+ (void)playSettingsClosedSound;
+ (void)playSettingsOpenedSound;
+ (void)playFlipCameraFlipEndSound;
+ (void)playFlipCameraFlipStartSound;
+ (void)playReplySound;
+ (void)playShakeToUndoSound;
+ (void)playCameraLandSound;
+ (void)playCameraSwishSound;
+ (void)playStartCameraSound;
+ (void)playScrollSoundSound;
+ (void)onApplicationDidEnterBackground:(id)arg1;
+ (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
+ (void)playSoundWithName:(id)arg1 extension:(id)arg2 volume:(float)arg3;
+ (void)playSoundWithName:(id)arg1 volume:(float)arg2;

@end

