//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString;

@interface TextTableViewCell : UITableViewCell
{
    NSString *_lastSizedString;
    struct CGSize _stringSize;
}

+ (struct CGSize)textSizeForWidth:(float)arg1 withText:(id)arg2;
+ (float)heightForWidth:(float)arg1 withText:(id)arg2;
+ (id)textLabelFont;
@property(nonatomic) struct CGSize stringSize; // @synthesize stringSize=_stringSize;
@property(copy, nonatomic) NSString *lastSizedString; // @synthesize lastSizedString=_lastSizedString;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

