//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TextFieldTableViewCell;

@protocol TextFieldTableViewCellDelegate <NSObject>
- (void)textFieldCellDidTapReturn:(TextFieldTableViewCell *)arg1;
- (void)textFieldCell:(TextFieldTableViewCell *)arg1 didChangeText:(NSString *)arg2;

@optional
- (BOOL)textFieldCell:(TextFieldTableViewCell *)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(NSString *)arg3;
@end

