//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "User.h"

@class NSString;

@interface TransientUser : NSObject <User>
{
    BOOL _blocked;
    NSString *_remoteID;
    NSString *_shortName;
    NSString *_fullName;
    NSString *_profilePictureURL;
    NSString *_countryCode;
    NSString *_nationalNumber;
    int _searchableStatus;
}

@property(nonatomic) int searchableStatus; // @synthesize searchableStatus=_searchableStatus;
@property(nonatomic) BOOL blocked; // @synthesize blocked=_blocked;
@property(copy, nonatomic) NSString *nationalNumber; // @synthesize nationalNumber=_nationalNumber;
@property(copy, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(copy, nonatomic) NSString *profilePictureURL; // @synthesize profilePictureURL=_profilePictureURL;
@property(copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(copy, nonatomic) NSString *shortName; // @synthesize shortName=_shortName;
@property(copy, nonatomic) NSString *remoteID; // @synthesize remoteID=_remoteID;
- (void).cxx_destruct;
@property(readonly) NSString *phoneNumber;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;

@end

