//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TrayManagementViewController, User;

@protocol TrayManagementViewControllerDelegate <NSObject>
- (void)trayManagementViewController:(TrayManagementViewController *)arg1 wantsToSendVideoToUser:(User *)arg2;
- (void)trayManagementViewControllerWantsToCancelRecordingVideo:(TrayManagementViewController *)arg1;
- (void)trayManagementViewControllerStartRecordingVideo:(TrayManagementViewController *)arg1 forUser:(User *)arg2;
- (BOOL)trayManagementViewController:(TrayManagementViewController *)arg1 canStartRecordingVideoForUser:(User *)arg2;
- (void)trayManagementViewController:(TrayManagementViewController *)arg1 wantsToSendPhotoToUser:(User *)arg2;
- (void)trayManagementViewControllerWillEndManagement:(TrayManagementViewController *)arg1;
- (void)trayManagementViewControllerWillBeginManagement:(TrayManagementViewController *)arg1;

@optional
- (BOOL)trayManagementViewControllerShouldBeginManagement:(TrayManagementViewController *)arg1;
@end

