//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NavigationController.h"

#import "ContactsViewControllerDelegate.h"
#import "JRModelManagerSubscriber.h"
#import "SettingsViewControllerDelegate.h"
#import "SubviewsOnlyHitViewDelegate.h"
#import "TrayViewDelegate.h"

@class CrystalBackgroundView, TrayView, UIButton, UIImageView, UILabel, UIView, User;

@interface TrayManagementViewController : NavigationController <TrayViewDelegate, ContactsViewControllerDelegate, SettingsViewControllerDelegate, SubviewsOnlyHitViewDelegate, JRModelManagerSubscriber>
{
    BOOL _hidesGradient;
    BOOL _didForceEndLastVideoRecording;
    BOOL _enableAddFriends;
    id <TrayManagementViewControllerDelegate> _delegate;
    float _topContentInset;
    UIButton *_manageButton;
    CrystalBackgroundView *_backgroundView;
    UIView *_actionSheet;
    UIImageView *_gradientView;
    UIImageView *_deleteVortex;
    UILabel *_dragLabel;
    TrayView *_trayView;
    UIButton *_addFriendsButton;
    UIView *_noFriendsView;
    UIButton *_noFriendsButton;
    UIButton *_settingsButton;
    UIButton *_doneButton;
    User *_pressedVideoUser;
    int _state;
    int _previousState;
}

@property(nonatomic) BOOL enableAddFriends; // @synthesize enableAddFriends=_enableAddFriends;
@property(nonatomic) int previousState; // @synthesize previousState=_previousState;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) BOOL didForceEndLastVideoRecording; // @synthesize didForceEndLastVideoRecording=_didForceEndLastVideoRecording;
@property(retain, nonatomic) User *pressedVideoUser; // @synthesize pressedVideoUser=_pressedVideoUser;
@property(retain, nonatomic) UIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) UIButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(retain, nonatomic) UIButton *noFriendsButton; // @synthesize noFriendsButton=_noFriendsButton;
@property(retain, nonatomic) UIView *noFriendsView; // @synthesize noFriendsView=_noFriendsView;
@property(retain, nonatomic) UIButton *addFriendsButton; // @synthesize addFriendsButton=_addFriendsButton;
@property(retain, nonatomic) TrayView *trayView; // @synthesize trayView=_trayView;
@property(retain, nonatomic) UILabel *dragLabel; // @synthesize dragLabel=_dragLabel;
@property(retain, nonatomic) UIImageView *deleteVortex; // @synthesize deleteVortex=_deleteVortex;
@property(retain, nonatomic) UIImageView *gradientView; // @synthesize gradientView=_gradientView;
@property(retain, nonatomic) UIView *actionSheet; // @synthesize actionSheet=_actionSheet;
@property(retain, nonatomic) CrystalBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIButton *manageButton; // @synthesize manageButton=_manageButton;
@property(nonatomic) float topContentInset; // @synthesize topContentInset=_topContentInset;
@property(nonatomic) BOOL hidesGradient; // @synthesize hidesGradient=_hidesGradient;
@property(nonatomic) __weak id <TrayManagementViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)resultsUpdatedForRequest:(id)arg1 results:(id)arg2 changes:(id)arg3;
- (void)settingsViewControllerDidFinish:(id)arg1;
- (void)contactsViewControllerDidFinish:(id)arg1;
- (void)trayView:(id)arg1 didEndMovingUser:(id)arg2;
- (struct CGPoint)trayViewDeleteEndpoint:(id)arg1;
- (BOOL)trayView:(id)arg1 shouldDeleteUserThrownWithVelocity:(struct CGPoint)arg2;
- (BOOL)trayView:(id)arg1 shouldDeleteUserDraggedToPoint:(struct CGPoint)arg2;
- (void)trayView:(id)arg1 didBeginMovingUser:(id)arg2;
- (void)trayView:(id)arg1 didEndPressOnUser:(id)arg2 wasCancelled:(BOOL)arg3;
- (void)trayView:(id)arg1 didStartPressOnUser:(id)arg2;
- (BOOL)trayView:(id)arg1 shouldStartPressOnUser:(id)arg2;
- (void)trayView:(id)arg1 didTapUser:(id)arg2;
- (void)trayViewDidLoadFavorites:(id)arg1;
- (void)setGearButtonHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)exitSettingsModeAnimated:(BOOL)arg1;
- (void)enterSettingsModeAnimated:(BOOL)arg1;
- (void)exitAddRemoveModeAnimated:(BOOL)arg1;
- (void)enterAddRemoveModeAnimated:(BOOL)arg1 fromRegistration:(BOOL)arg2;
- (void)exitManagementModeAnimated:(BOOL)arg1;
- (void)enterManagementModeAnimated:(BOOL)arg1;
- (void)onNoFriendsButtonTapped:(id)arg1;
- (void)onAddFriendsButtonTapped:(id)arg1;
- (void)onSettingsButtonTapped:(id)arg1;
- (void)onSettingsButtonTouchDown:(id)arg1;
- (void)onManagementButtonTapped:(id)arg1;
- (void)enterAddRemoveModeFromRegistration:(BOOL)arg1;
- (void)exitManagementMode;
- (void)forceStopCurrentRecording;
- (BOOL)subviewsOnlyHitView:(id)arg1 shouldHitForSubview:(id)arg2 atPoint:(struct CGPoint)arg3;
- (void)viewDidLoad;
- (void)loadView;

@end

