//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGDynamicCollectionViewDataSource.h"
#import "IGDynamicCollectionViewDelegate.h"
#import "JRModelManagerSubscriber.h"
#import "RecipientCellDelegate.h"
#import "SubviewsOnlyHitViewDelegate.h"

@class DynamicCollectionView, NSArray, NSMapTable, UIPageControl, User;

@interface TrayView : UIView <IGDynamicCollectionViewDataSource, IGDynamicCollectionViewDelegate, JRModelManagerSubscriber, RecipientCellDelegate, SubviewsOnlyHitViewDelegate>
{
    BOOL _editing;
    BOOL _suspendContentReload;
    BOOL _shouldDeleteDraggedUser;
    id <TrayViewDelegate> _delegate;
    NSArray *_recipients;
    DynamicCollectionView *_collectionView;
    User *_pressedUser;
    NSMapTable *_recipientViews;
    UIPageControl *_pageControl;
}

@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) BOOL shouldDeleteDraggedUser; // @synthesize shouldDeleteDraggedUser=_shouldDeleteDraggedUser;
@property(retain, nonatomic) NSMapTable *recipientViews; // @synthesize recipientViews=_recipientViews;
@property(retain, nonatomic) User *pressedUser; // @synthesize pressedUser=_pressedUser;
@property(retain, nonatomic) DynamicCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) BOOL suspendContentReload; // @synthesize suspendContentReload=_suspendContentReload;
@property(retain, nonatomic) NSArray *recipients; // @synthesize recipients=_recipients;
@property(nonatomic, getter=isEditing) BOOL editing; // @synthesize editing=_editing;
@property(nonatomic) __weak id <TrayViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)onMessageSent:(id)arg1;
- (void)applicationBecameActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)resultsUpdatedForRequest:(id)arg1 results:(id)arg2 changes:(id)arg3;
- (void)recipientCellDidFinishPress:(id)arg1 wasCancelled:(BOOL)arg2;
- (BOOL)recipientCellShouldStartPress:(id)arg1;
- (void)recipientCellDidStartPress:(id)arg1;
- (void)recipientCellWasTapped:(id)arg1;
- (struct CGPoint)collectionView:(id)arg1 didDeleteView:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldDeleteView:(id)arg2 afterThrowWithVelocity:(struct CGPoint)arg3;
- (BOOL)collectionView:(id)arg1 shouldDeleteViewAfterMove:(id)arg2;
- (void)collectionView:(id)arg1 didEndMovingView:(id)arg2;
- (void)collectionView:(id)arg1 willBeginMovingView:(id)arg2;
- (void)collectionView:(id)arg1 willDisplayView:(id)arg2;
- (void)collectionView:(id)arg1 didMoveItemFromIndex:(int)arg2 toIndex:(int)arg3;
- (BOOL)collectionView:(id)arg1 canMoveItemFromIndex:(int)arg2 toIndex:(int)arg3;
- (BOOL)collectionView:(id)arg1 canMoveItemAtIndex:(int)arg2;
- (void)collectionView:(id)arg1 didPage:(int)arg2;
- (void)configureCell:(id)arg1;
- (id)viewForCollectionView:(id)arg1 atIndex:(int)arg2;
- (int)numberOfViewsForCollectionView:(id)arg1;
- (void)onPageControlChangedValue:(id)arg1;
- (void)reloadDataAnimated:(BOOL)arg1;
- (BOOL)subviewsOnlyHitView:(id)arg1 shouldHitForSubview:(id)arg2 atPoint:(struct CGPoint)arg3;
- (void)spinRecipient:(id)arg1;
- (void)animateCapturedImage:(id)arg1 intoUser:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

