//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TrayView, User;

@protocol TrayViewDelegate <NSObject>
- (struct CGPoint)trayViewDeleteEndpoint:(TrayView *)arg1;
- (BOOL)trayView:(TrayView *)arg1 shouldDeleteUserThrownWithVelocity:(struct CGPoint)arg2;
- (BOOL)trayView:(TrayView *)arg1 shouldDeleteUserDraggedToPoint:(struct CGPoint)arg2;
- (void)trayView:(TrayView *)arg1 didEndMovingUser:(User *)arg2;
- (void)trayView:(TrayView *)arg1 didBeginMovingUser:(User *)arg2;
- (void)trayView:(TrayView *)arg1 didEndPressOnUser:(User *)arg2 wasCancelled:(BOOL)arg3;
- (void)trayView:(TrayView *)arg1 didStartPressOnUser:(User *)arg2;
- (BOOL)trayView:(TrayView *)arg1 shouldStartPressOnUser:(User *)arg2;
- (void)trayView:(TrayView *)arg1 didTapUser:(User *)arg2;
- (void)trayViewDidLoadFavorites:(TrayView *)arg1;
@end

