//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (BoltColors)
+ (id)pp_darkTitleFontColor;
+ (id)pp_darkSeparatorColor;
+ (id)pp_lightSeparatorColor;
+ (id)pp_redColor;
+ (id)pp_lightGrayColor;
+ (id)pp_offWhiteColor;
+ (id)pp_lightBlueColor;
+ (id)pp_greenColor;
+ (id)pp_blueColor;
+ (id)pp_tintColor;
@end

