//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (PPFonts)
+ (id)pp_messageFont;
+ (float)pp_messageMaxFontSize;
+ (id)pp_boldCameraInstructionsFont;
+ (id)pp_cameraInstructionsFont;
+ (id)pp_onboardingFinePrintLinkFont;
+ (id)pp_onboardingFinePrintFont;
+ (id)pp_onboardingDescriptionFont;
+ (id)pp_onboardingTextFieldBoldFont;
+ (id)pp_onboardingTextFieldFont;
+ (id)pp_onboardingTitleFont;
+ (id)pp_onboardingTitleLargeFont;
+ (id)pp_onboardingButtonFont;
+ (id)pp_lightFontOfSize:(float)arg1;
+ (id)pp_boldFontOfSize:(float)arg1;
+ (id)pp_fontOfSize:(float)arg1;
@end

