//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (PPPixelBuffer)
+ (id)pp_imageWithPixelBuffer:(struct __CVBuffer *)arg1 orientation:(int)arg2;
+ (id)pp_imageWithPixelBuffer:(struct __CVBuffer *)arg1;
- (id)pp_imageWithTransform:(struct CGAffineTransform)arg1;
@end

