//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (PPRounded)
- (id)pp_roundedImageWithCornerRadius:(float)arg1;
- (id)pp_roundedImageOfSize:(struct CGSize)arg1 borderColor:(id)arg2 borderWidth:(float)arg3 shadowSize:(float)arg4 shadowAlpha:(float)arg5;
@end

