//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (PPBorders)
- (void)pp_removeFrames;
- (void)pp_displayFramesWithDepth:(int)arg1;
- (void)pp_displayFrames;
- (void)pp_addBottomDarkBorder;
- (void)pp_addBottomBorder;
- (void)pp_addTopBorder;
@end

