//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (PPAnimations)
- (void)pp_bouncyHide;
- (void)pp_bouncyShowWithCompletion:(CDUnknownBlockType)arg1;
- (void)pp_bouncyShow;
@end

