//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JRModelManagerSubscriber.h"

@class NSMapTable, Reachability;

@interface Uploader_ : NSObject <JRModelManagerSubscriber>
{
    BOOL _retryScheduled;
    Reachability *_reachability;
    NSMapTable *_uploads;
}

+ (void)markMessageAsUploaded:(id)arg1 withRemoteID:(id)arg2 mediaURL:(id)arg3;
+ (void)setDisabled:(BOOL)arg1;
+ (void)cancelAllUploads;
+ (BOOL)cancelUploadOfMessage:(id)arg1;
+ (void)start;
+ (id)sharedInstance;
@property(nonatomic) BOOL retryScheduled; // @synthesize retryScheduled=_retryScheduled;
@property(retain, nonatomic) NSMapTable *uploads; // @synthesize uploads=_uploads;
@property(retain, nonatomic) Reachability *reachability; // @synthesize reachability=_reachability;
- (void).cxx_destruct;
- (void)resultsUpdatedForRequest:(id)arg1 results:(id)arg2 changes:(id)arg3;
- (void)markMessageAsUploaded:(id)arg1 withRemoteID:(id)arg2 mediaURL:(id)arg3;
- (void)uploadMessage:(id)arg1;
- (void)uploadNewMessageForMessage:(id)arg1;
- (void)uploadReplyMessage:(id)arg1;
- (void)cancelAllUploads;
- (BOOL)cancelUploadOfMessage:(id)arg1;
- (void)scheduleRetryForFailedMessage:(id)arg1;
- (void)uploadMessages;
- (void)applicationBecameActive:(id)arg1;
- (id)init;
- (void)dealloc;

@end

