//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURLResponse, NSURLSessionTask;

@interface URLConnection : NSObject
{
    NSURLSessionTask *_task;
    int _downloadLength;
    NSURLResponse *_response;
    CDUnknownBlockType _uploadProgressBlock;
    CDUnknownBlockType _downloadProgressBlock;
}

+ (id)sendBackgroundUploadAPIRequest:(id)arg1 withUuid:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (id)sendAsynchronousRequest:(id)arg1 withOutputPath:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (id)sendAsynchronousRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (id)connectionQueue;
@property(copy, nonatomic) CDUnknownBlockType downloadProgressBlock; // @synthesize downloadProgressBlock=_downloadProgressBlock;
@property(copy, nonatomic) CDUnknownBlockType uploadProgressBlock; // @synthesize uploadProgressBlock=_uploadProgressBlock;
@property(retain, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(nonatomic) int downloadLength; // @synthesize downloadLength=_downloadLength;
@property(retain, nonatomic) NSURLSessionTask *task; // @synthesize task=_task;
- (void).cxx_destruct;
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;
- (void)cancel;

@end

