//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TransientUser, UserSearchViewController;

@protocol UserSearchViewControllerDelegate <NSObject>
- (void)userSearchViewControllerDidTapCancel:(UserSearchViewController *)arg1;
- (void)userSearchViewController:(UserSearchViewController *)arg1 didSelectUser:(TransientUser *)arg2;

@optional
- (void)userSearchViewController:(UserSearchViewController *)arg1 willShowUser:(TransientUser *)arg2;
@end

