//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Users : NSObject
{
    int _favoritesUpdatingCount;
}

+ (void)setFavoritesUploadingPaused:(BOOL)arg1;
+ (void)searchForUserWithCountryCode:(id)arg1 nationalNumber:(id)arg2 completion:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (void)uploadPhoneNumbersAndNames:(id)arg1 withWaterfall:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)start;
+ (id)sharedInstance;
@property(nonatomic) int favoritesUpdatingCount; // @synthesize favoritesUpdatingCount=_favoritesUpdatingCount;
- (void)uploadFavorites:(id)arg1;
- (void)uploadPhoneNumbersAndNames:(id)arg1 withWaterfall:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)saveList:(id)arg1 forKey:(id)arg2;
- (void)deleteListForKey:(id)arg1;
- (id)listForKey:(id)arg1;
- (id)prefsPathForKey:(id)arg1;
- (void)setFavoritesUploadingPaused:(BOOL)arg1;
- (void)onDidChangeCurrentUser:(id)arg1;
- (void)onDidEnterBackground:(id)arg1;
- (id)init;
- (void)dealloc;

@end

