//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class AvatarImageView, UIImageView, UIView, User;

@interface UserCell : UITableViewCell
{
    User *_user;
    UIView *_bottomBorderView;
    int _visbleStatusMode;
    AvatarImageView *_avatarView;
    UIImageView *_statusView;
}

+ (float)defaultHeight;
@property(retain, nonatomic) UIImageView *statusView; // @synthesize statusView=_statusView;
@property(retain, nonatomic) AvatarImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(nonatomic) int visbleStatusMode; // @synthesize visbleStatusMode=_visbleStatusMode;
@property(retain, nonatomic) UIView *bottomBorderView; // @synthesize bottomBorderView=_bottomBorderView;
@property(retain, nonatomic) User *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateStatusAnimated:(BOOL)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

