//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JRModel.h"

#import "User.h"

@class NSDate, NSString;

@interface User : JRModel <User>
{
}

- (void)setFavorite:(BOOL)arg1 clearOrderstamp:(BOOL)arg2;
@property(readonly) NSString *phoneNumber;
@property(readonly) NSString *relationshipBasedDisplayName;
- (id)manager;

// Remaining properties
@property BOOL blocked; // @dynamic blocked;
@property(readonly) NSString *countryCode; // @dynamic countryCode;
@property BOOL favorite; // @dynamic favorite;
@property(readonly) NSString *fullName; // @dynamic fullName;
@property BOOL inAddressBook; // @dynamic inAddressBook;
@property(readonly) NSDate *lastContactDate; // @dynamic lastContactDate;
@property(readonly) NSString *nationalNumber; // @dynamic nationalNumber;
@property int orderstamp; // @dynamic orderstamp;
@property(readonly) NSString *profilePictureURL; // @dynamic profilePictureURL;
@property(readonly) NSString *remoteID; // @dynamic remoteID;
@property(readonly) NSString *shortName; // @dynamic shortName;

@end

