//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAssetWriter, AVAssetWriterInput, NSMutableArray;

@interface VideoRecorder : NSObject
{
    BOOL _used;
    BOOL _acceptsSamples;
    BOOL _sessionStarted;
    AVAssetWriter *_writer;
    AVAssetWriterInput *_videoInput;
    AVAssetWriterInput *_audioInput;
    NSMutableArray *_earlyAudioBuffers;
    int _numberOfVideoBuffers;
    int _numberOfAudioBuffers;
}

@property(nonatomic) int numberOfAudioBuffers; // @synthesize numberOfAudioBuffers=_numberOfAudioBuffers;
@property(nonatomic) int numberOfVideoBuffers; // @synthesize numberOfVideoBuffers=_numberOfVideoBuffers;
@property(retain, nonatomic) NSMutableArray *earlyAudioBuffers; // @synthesize earlyAudioBuffers=_earlyAudioBuffers;
@property(retain, nonatomic) AVAssetWriterInput *audioInput; // @synthesize audioInput=_audioInput;
@property(retain, nonatomic) AVAssetWriterInput *videoInput; // @synthesize videoInput=_videoInput;
@property(retain, nonatomic) AVAssetWriter *writer; // @synthesize writer=_writer;
@property(nonatomic) BOOL sessionStarted; // @synthesize sessionStarted=_sessionStarted;
@property(nonatomic) BOOL acceptsSamples; // @synthesize acceptsSamples=_acceptsSamples;
@property(nonatomic) BOOL used; // @synthesize used=_used;
- (void).cxx_destruct;
- (void)stopWritingWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)appendAudioSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (BOOL)appendVideoSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (BOOL)startWritingVideoToUrl:(id)arg1 transform:(struct CGAffineTransform)arg2 outputSize:(struct CGSize)arg3;

@end

