//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "VideoPlayerDelegate.h"

@class AVAsset, UIImage, VideoPlayer;

@interface VideoPlaybackView : UIView <VideoPlayerDelegate>
{
    BOOL _isPlaying;
    VideoPlayer *_videoPlayer;
}

@property(retain, nonatomic) VideoPlayer *videoPlayer; // @synthesize videoPlayer=_videoPlayer;
@property(nonatomic) BOOL isPlaying; // @synthesize isPlaying=_isPlaying;
- (void).cxx_destruct;
- (void)videoPlayerDidFinishPlaying:(id)arg1;
@property(retain, nonatomic) AVAsset *asset;
- (void)setMuted:(BOOL)arg1;
- (void)pause;
- (void)onDidEnterBackground:(id)arg1;
- (void)play;
- (void)seekToPosition:(float)arg1;
- (void)prepareToPlayWithCallback:(CDUnknownBlockType)arg1;
@property(nonatomic) BOOL loop;
@property(readonly, nonatomic) UIImage *image;
- (void)layoutSubviews;
- (void)dealloc;

@end

