//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MediaCardView.h"

@class VideoPlaybackView;

@interface VideoCardView : MediaCardView
{
    BOOL _isFrontmost;
    BOOL _loadMediaOnAppForeground;
    VideoPlaybackView *_player;
    VideoCardView *_strongSelf;
}

@property(retain, nonatomic) VideoCardView *strongSelf; // @synthesize strongSelf=_strongSelf;
@property(nonatomic) BOOL loadMediaOnAppForeground; // @synthesize loadMediaOnAppForeground=_loadMediaOnAppForeground;
@property(nonatomic) BOOL isFrontmost; // @synthesize isFrontmost=_isFrontmost;
@property(retain, nonatomic) VideoPlaybackView *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)onDismissTapped:(id)arg1;
- (void)handleExitingBlur;
- (void)handleEnteringBlur;
- (void)prepareBlurredViewForDisplay;
- (void)handleBeingDismissed;
- (void)handleBecomingFrontmostCard;
- (void)muteStateChanged:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)video:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)writeMediaToCameraRoll;
- (void)prepareToPlay;
- (void)loadMessageMedia;
- (void)setMessage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

