//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVPlayerItemOutputPullDelegate.h"

@class AVAsset, AVPlayer, AVPlayerItem, AVPlayerLayer;

@interface VideoPlayer : NSObject <AVPlayerItemOutputPullDelegate>
{
    BOOL _loop;
    BOOL _muted;
    BOOL _seeking;
    BOOL _shouldPlay;
    BOOL _isPreloading;
    AVAsset *_asset;
    id <VideoPlayerDelegate> _delegate;
    AVPlayerLayer *_playerLayer;
    AVPlayer *_player;
    AVPlayerItem *_playerItem;
    CDStruct_1b6d18a9 _seekTime;
    CDStruct_e83c9415 _playbackRange;
}

@property(nonatomic) CDStruct_e83c9415 playbackRange; // @synthesize playbackRange=_playbackRange;
@property(nonatomic) BOOL isPreloading; // @synthesize isPreloading=_isPreloading;
@property(nonatomic) BOOL shouldPlay; // @synthesize shouldPlay=_shouldPlay;
@property(nonatomic) CDStruct_1b6d18a9 seekTime; // @synthesize seekTime=_seekTime;
@property(nonatomic, getter=isSeeking) BOOL seeking; // @synthesize seeking=_seeking;
@property(nonatomic) BOOL muted; // @synthesize muted=_muted;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) AVPlayerLayer *playerLayer; // @synthesize playerLayer=_playerLayer;
@property(nonatomic) BOOL loop; // @synthesize loop=_loop;
@property(nonatomic) __weak id <VideoPlayerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
- (void).cxx_destruct;
- (void)outputSequenceWasFlushed:(id)arg1;
- (void)outputMediaDataWillChange:(id)arg1;
- (void)itemDidFinishPlaying:(id)arg1;
- (CDStruct_1b6d18a9)playbackEndTime;
- (void)pause;
- (void)playFromStart;
- (void)play;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1;
- (void)prepareToPlayWithCallback:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) CDStruct_1b6d18a9 currentTime;
- (id)initWithAsset:(id)arg1;
- (void)dealloc;

@end

