//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class HeaderView, HeaderViewButton, UIActivityIndicatorView, UIWebView;

@interface WebViewController : UIViewController <UIWebViewDelegate>
{
    id <WebViewControllerDelegate> _delegate;
    HeaderView *_headerView;
    UIWebView *_webView;
    HeaderViewButton *_reloadButton;
    UIActivityIndicatorView *_spinner;
}

@property(retain, nonatomic) UIActivityIndicatorView *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) HeaderViewButton *reloadButton; // @synthesize reloadButton=_reloadButton;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) HeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak id <WebViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)onReloadButtonTapped:(id)arg1;
- (void)onDismissButtonTapped:(id)arg1;
- (void)viewDidLoad;
- (id)initWithURL:(id)arg1 title:(id)arg2;

@end

